### ISSUE TITLE
Содержимое папки temporary

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#100]
Что именно хранится в c:\Users\User\AppData\Roaming\Mozilla\Firefox\Profiles\profile.default\storage\temporary\ и возможно ли задать полную очистку этой папки пр закрытии браузера?

**Comment by The-OP** [comment]
>Что именно хранится

IndexedDB с флагом temporary, скомпилированный asm.js. Возможно, что-то еще.

>возможно ли задать полную очистку этой папки пр закрытии браузера?

Если Ctrl+Shift+Del удаляет ее, то возможно - прямо через стандартные Preferences.

**Comment by AlxMxlA** [comment]
>> прямо через стандартные Preferences
У меня в about:preferences#privacy выставлено:
- всегда работать в режиме приватного просмотра
- принимать куки с сайтов - никогда
- сохранять куки до закрытия мною Firefox.
Если это имелось в виду, то после закрытия ничего не удаляется.

**Comment by The-OP** [comment]
Ну значит осталось asm.js отключить.

**Comment by AlxMxlA** [comment]
> Ну значит осталось asm.js отключить.
Что такое asm.js и как его отключить?

**Comment by The-OP** [comment]
https://github.com/The-OP/Fox/blob/master/prefs/prefs_4.js#L170
