### ISSUE TITLE
permission "offline-app"

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#102]
Возможно ли через какой-нибудь параметр наполнять с выбранными флагами Автономные данные в about:preferences#advanced -> Сеть -> Автономное веб-содержимое и данные пользователя -> Исключения (проще говоря - создавать заранее список сайтов (в том же user.js), которым разрешено/запрещено сохранять данные для работы в автономном режиме) кроме как отвечая на запросы браузера при
`user_pref("offline-apps.allow_by_default", false);

user_pref("browser.offline-apps.notify, false);`?

**Comment by The-OP** [comment]
Можно сделать как [здесь](https://github.com/The-OP/Fox/blob/master/prefs/prefs_1.js#L326).

**Comment by AlxMxlA** [comment]
Если речь идёт о user_pref("permissions.manager.defaultsUrl", ""), то особой пользы от него нет.
У меня, по крайней мере, с моими настройками, при которых Автономное веб-содержимое и данные пользователя -> Исключения после каждой сессии наполняется (если необходимо) заново. Не критично, но не достаточно удобно.
К примеру, по настройке browser.newtabpage.pinned у меня есть сайт, чьи автономные данные я не хочу сохранять. Но они всё равно сохраняются, потому что сначала срабатывает browser.newtabpage.pinned из user.js, а уже потом я, может быть, открываю сайт и уже тогда только я получаю от браузера запрос на сохранения данных (который отклоняю, конечно, но уже поздно).

**Comment by The-OP** [comment]
Речь идет о задании своего списка пермишнов через data URI, как в примере там.

**Comment by AlxMxlA** [comment]
>> через data URI

Что такое data URI?

**Comment by The-OP** [comment]
По вышеприведенной ссылке написано. Рекомендую пройти и прочитать.
