### ISSUE TITLE
privacy.userContext.enabled

### ISSUE THREAD

**Issue by KOLANICH** [The-OP/Fox#103]

**Comment by The-OP** [comment]
Оно еще не доделано. Доделают - включат.

**Comment by KOLANICH** [comment]
Фичу это ничем не портит.

**Comment by The-OP** [comment]
Ты ей пользуешься? Начиная с какой версии работает?

**Comment by KOLANICH** [comment]
В esr уже.

**Comment by The-OP** [comment]
Судя по информации [отсюда](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities), работает с 53. Окей, можно добавить. Только не знаю куда - в FAQ? "Как семенить с нескольких аккаунтов?"

**Comment by The-OP** [comment]
1ea1bda
