### ISSUE TITLE
Проверка аддонов при выходе новой версии.

### ISSUE THREAD

**Issue by leedoyle** [The-OP/Fox#106]
Есть идея проверять работу упомянутых в шапке аддонов при выходе новой версии. Например, тот же [Custom Buttons](https://github.com/The-OP/Fox/pull/105/commits/da26fd4d60f8dbd27ed4240225b41bbd4d49780b) отвалился в Firefox 51, а в шапке это не было отражено.
Если аддон работает в ESR, то оставлять его и упоминать об этом, если нет — помечать как нерабочий, выжидать разумное время (месяц? два?) и удалять.

Как пример работающего в ESR, но не работающего в stable лисе аддона - Vimperator. (Его в шапке нет, но его аудитория, наверное, и так про него знает).

**Comment by The-OP** [comment]
Пожалуйста, проверяй.

**Comment by dartraiden** [comment]
Вимператор уже починили, если я правильно понимаю.

**Comment by leedoyle** [comment]
Пару дней назад c АМО удалили Clean Links с мотивировкой "не работает" (он был не e10s). По всей видимости просто проверили, работает ли в релизной лисе (вероятно со включённым e10s), и удалили...
Варианта два, либо пролинковать в шапке [гитхаб дополнения ](https://github.com/diegocr/CleanLinks), либо ждать версии с e10s на АМО

Связанные issue: https://github.com/mozilla/addons-server/issues/5073 
https://github.com/diegocr/CleanLinks/issues/170

**Comment by The-OP** [comment]
46be985
