### ISSUE TITLE
Утечка через WebRTC

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#107]
> // Запрещает работу WebRTC в режиме P2P, разрешая ее только через сервер третьей стороны, что
> // предотвращает утечку IP-адресов всех сетевых интерфейсов компьютера (подробнее - см. prefs_2).
> // https://wiki.mozilla.org/Media/WebRTC/Privacy
> // https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/
> // https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment
> user_pref("media.peerconnection.ice.relay_only", true);

Этого недостаточно. Начиная с Firefox 51, необходимо ещё сделать `media.peerconnection.ice.no_host = true`

см. https://github.com/gorhill/uBlock/issues/2337

Проверить можно [тут](https://browserleaks.com/webrtc#webrtc-disable): без второй опции виден локальный IP-шник.

**Comment by The-OP** [comment]
>media.peerconnection.ice.no_host

Видел эту штуку, но мне показалось, что она полезна только в связке с `default_address_only`, поэтому отложил до 52.2 ESR. Чего-то у них не то с таблицей в wiki. Спасибо за информацию.

532da31

**Comment by dartraiden** [comment]
Алсо если я правильно понимаю, теперь можно раскомментировать

`//user_pref("media.peerconnection.ice.default_address_only", true);`

и убрать `user_pref("media.peerconnection.ice.relay_only", true);`

**Comment by The-OP** [comment]
>теперь можно раскомментировать
Да, ждем 52.2 ESR: #54.
