### ISSUE TITLE
Избыточность настроек?

### ISSUE THREAD

**Issue by HouyiTheArcher** [The-OP/Fox#108]
Есть ли смысл в изменении дополнительных параметров, если основной (логическая переменная) уже переведён в "false"? Например, в части с Predictor'ом (Seer) разве недостаточно просто выставить "user_pref("network.predictor.enabled", false);" и "user_pref("network.predictor.enable-prefetch", false);", или нужно обязательно проставлять и параметры "confidence"?

**Comment by The-OP** [comment]
Лучше перебдеть чем недобдеть.

**Comment by Aonavan** [comment]
@The-OP может перенести их в prefs_0.js на радость нам, недобдетелям?
