### ISSUE TITLE
user_pref("network.http.referer.spoofSource", true) + Decentraleyes = ломают mail.yandex.ru и disk.yandex.ru

### ISSUE THREAD

**Issue by userneu** [The-OP/Fox#109]
SUBJ

**Comment by pavlogafy** [comment]
какие настройки из pref_X.js установлены? Отключение только network.http.referer.spoofSource помогает?

**Comment by userneu** [comment]
Много каких. Все по местному гайду. Не знаю насчет только, но отключение именно этой опции помогает. Я экспериментировал с настройками из блока Referer-ов. Было так:
```
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.referer.trimmingPolicy", 2);
user_pref("network.http.sendRefererHeader", 2);
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("network.http.referer.XOriginTrimmingPolicy", 0);
user_pref("network.http.sendSecureXSiteReferrer", true);
user_pref("network.http.enablePerElementReferrer", false);
```
Перебрал среди них и выяснил что именно переключение спуфСорса исправляет проблему. На Рефереры вообще навел сам автор Decentraleyes. Я ему отписал в ответ, но он пока молчит.

**Comment by The-OP** [comment]
А по отдельности?

Decentraleyes вообще много что может ломать.

**Comment by userneu** [comment]
Что значит по отдельности? При включенной опции отключаю аддон - сервис работает. И наоборот - отключаю опцию при работающем аддоне - все работает. 
>Decentraleyes вообще много что может ломать.
За все не скажу. А вот описанный мною конфликт я бы отметил где-нибудь

**Comment by The-OP** [comment]
e11828f

**Comment by userneu** [comment]
Только "слово" спуфинг в поиске не ищется. Я бы указал как у меня в сабже - команда+аддон.

**Comment by The-OP** [comment]
Ну там общая секция для того, что может сломаться от любых манипуляций с реферером. Может заменить на "Изменение referer"? Последнее слово ищется в поиске.
