### ISSUE TITLE
Вопрос о uBlock Origin

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#11]
Ввиду этой новости http://www.opennet.ru/opennews/art.shtml?num=42432
Весьма спорное решение. На SF есть не мало проектов, не мало ссылок ведут туда. На PortableApps вообще все ссылки туда ведут.

**Comment by firefoxForUser** [comment]
http://www.opennet.ru/opennews/art.shtml?num=42457

**Comment by firefoxForUser** [comment]
/*
 * Классический вид страницы ошибки соединения.
 */
user_pref("browser.xul.error_pages.enabled", true);

/*
 * Классический вид страницы ошибки сертификата.
 */
user_pref("browser.xul.error_pages.expert_bad_cert", true);

причем последняя настройка показывает кнопку с добавлением сертификата в отличии от новой версии (но сам не тестил)

**Comment by The-OP** [comment]
По первой ссылке - одно из преимуществ Origin (strict blocking). В форке его нет из-за чего, например, подписка Malware Domains (включающая в себя домены из Safebrowsing) там бесполезна. Да и возможность добавления исключения есть.

По второй - так автору uBlock Origin напиши.
