### ISSUE TITLE
Tampermonkey и его обфускация кода

### ISSUE THREAD

**Issue by myBestSoftAndPref** [The-OP/Fox#115]
Вопрос насчет того уверены ли вы что там именно обфускация кода? И хотелось бы увидеть ссылки насчет этого.

Дело в том, что есть сервисы вроде: https://closure-compiler.appspot.com/home
Которые минимизируют код, заменяя имена переменных короткими и заменяя некоторые последовательности кода более короткими аналогами.
Вообще вряд ли это необходимо для расширений, это нужно сайтам, чтобы страница быстрее грузилась. Почему тогда он минимизирован? Дело в том, что есть плагины к различным средам которые собирают js скрипт из кусочков и автоматически минимизируют его. Возможно автор этого дополнения просто работает на настроенной среде и не заморачивается тем, что что-то там минимизируется.

**Comment by The-OP** [comment]
>вы

Можно на "ты".

>И хотелось бы увидеть ссылки насчет этого.

Так в архиве все видно.

>минимизируют код

Предположение справедливо только для свободных скриптов, у которых есть репозиторий с нормальными исходниками.

>Почему тогда он минимизирован?
>Возможно автор этого дополнения просто работает

Зачем все эти предположения? Бритва Оккама же. Кроме того, у проприетарщика по умолчанию нет кредита доверия. Кроме того, из гадостей там не только обфускация исходников. Короче, совершенно не понимаю, чего ты хочешь.
