### ISSUE TITLE
dom.enable_performance

### ISSUE THREAD

**Issue by PekaFat** [The-OP/Fox#116]
https://github.com/The-OP/Fox/blob/master/prefs/prefs_2.js
`// Отключает передачу браузером информации о времени начала и окончания загрузки страницы.
// https://wiki.mozilla.org/Security/Reviews/Firefox/NavigationTimingAPI
user_pref("dom.enable_performance", false);`

Этот конфиг ломает авторизацию на pornhub.com, может быть и на других сайтах, не тестил.

**Comment by The-OP** [comment]
8212073
