### ISSUE TITLE
browser.offline-apps.notify

### ISSUE THREAD

**Issue by PekaFat** [The-OP/Fox#117]
Настройка повторяется, в первом файле она true, во втором false.
Так же повторяется offline-apps.allow_by_default, но она везде false.

https://github.com/The-OP/Fox/blob/8212073b1d25602caddb76f5b7a39f98a7ccfd42/prefs/prefs_1.js
![image](https://cloud.githubusercontent.com/assets/13280748/25782625/a64801bc-335f-11e7-8c45-205a714384f1.png)

https://github.com/The-OP/Fox/blob/8212073b1d25602caddb76f5b7a39f98a7ccfd42/prefs/prefs_2.js
![image](https://cloud.githubusercontent.com/assets/13280748/25782627/b120e702-335f-11e7-88be-33174ecf5424.png)

**Comment by The-OP** [comment]
Так и задумано.
