### ISSUE TITLE
Спуфинг реферера и qiwi.com

### ISSUE THREAD

**Issue by PekaFat** [The-OP/Fox#118]
Ломает авторизацию на qiwi.com:
![default](https://cloud.githubusercontent.com/assets/13280748/25787415/31f16b2a-33b2-11e7-9e46-694a1fa209e6.PNG)

Значения настроек дефолтные из prefs_2.js.
Можете добавить в список "ломающие сайты настройки."

Я сильно удивлён, что это сломало киви, я логинился на 100 разных сайтах и всё было хорошо.

**Comment by The-OP** [comment]
980698f
