### ISSUE TITLE
Дубликат browser.safebrowsing.reportPhishURL в prefs_1.js

### ISSUE THREAD

**Issue by PekaFat** [The-OP/Fox#119]
https://github.com/The-OP/Fox/blob/master/prefs/prefs_1.js#L125

![default](https://cloud.githubusercontent.com/assets/13280748/25789651/335b6b80-33c3-11e7-885e-2cd96b747ea6.PNG)

**Comment by The-OP** [comment]
Хм, действительно.

a331cf9

**Comment by The-OP** [comment]
@PekaFat 
Зачем эти переименования и подчистки? Будь так добр, перестань заниматься ерундой.
