### ISSUE TITLE
Ещё настройки

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#12]
// Классический вид страницы ошибки соединения.
user_pref("browser.xul.error_pages.enabled", true);

// Классический вид страницы ошибки сертификата.
user_pref("browser.xul.error_pages.expert_bad_cert", true);

**Comment by firefoxForUser** [comment]
// Открывать вкладки вместо новых окон, открывать все ссылки в вкладках.
user_pref("browser.link.open_newwindow.restriction", 0);

Ну на самом деле вроде как не все. Некоторые попапы все же вылазят вместо окон каким-то образом. Может и ошибаюсь.

**Comment by The-OP** [comment]
>browser.xul.error_pages.enabled

Так оно же включено по умолчанию. Или имелось в виду false? С false вместо страницы выдается alert: "Firefox can't find the server at [...]".

>browser.xul.error_pages.expert_bad_cert

Можно скрин разницы между включенной и выключенной? А то навскидку не вспомню сайт с кривым сертификатом, чтобы потестить.

>browser.link.open_newwindow.restriction
[Пишут](https://support.mozilla.org/en-US/questions/957157), что некоторым сайтам от этого плохеет.

**Comment by firefoxForUser** [comment]
На счет `browser.xul.error_pages.enabled` ошибся, значение по умолчанию нормальное, вроде бы.

http://blog.johnath.com/2008/11/06/ssl-error-pages-in-firefox-31/ - скрин
описание http://kb.mozillazine.org/Browser.xul.error_pages.expert_bad_cert
Вот пример сайта, где проверить https://cacert.org/
если значение true, то кнопочка приема плохого сертификата видна сразу, без спойлера, инчае приходится нажимать.

Я `browser.link.open_newwindow.restriction` + принудительным однооконным режимом Tab Mix Plus пользуюсь уже 3 года. Проблем не видел ни разу, а вот рекламные окна, которые из-за группировки окон на панели замечаю не сразу удобно закрывать и случайных нажатий нету.

**Comment by The-OP** [comment]
e9dca78069
