### ISSUE TITLE
Stylus is a Stylish fork without analytics

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#120]
https://www.ghacks.net/2017/05/16/stylus-is-a-stylish-fork-without-analytics/
https://addons.mozilla.org/en-US/firefox/addon/styl-us/
https://github.com/schomery/stylish-chrome

**Comment by The-OP** [comment]
>Stylus collects nothing. Period.

Довольно категоричное заявление, учитывая [это](https://github.com/schomery/stylish-chrome/blob/master/background.js#L57).

Продолжаем пользоваться StylRRR.

**Comment by soredake** [comment]
@The-OP может я чего-то не вижу, но ниже выделенной строчки простое открытие ссылки при обновлении.

**Comment by The-OP** [comment]
Ну да, открытие с передачей версии аддона. То есть как минимум информацию об установках они собирают. Заявляя при этом, что "не собираем ничего и точка".

**Comment by 2ffz** [comment]
Кажется выпилили.

**Comment by soredake** [comment]
https://github.com/openstyles/stylus/blob/master/background/background.js#L50-L54

**Comment by soredake** [comment]
https://github.com/openstyles/stylus/blob/master/background/background.js#L71

**Comment by The-OP** [comment]
Новый вариант конечно лучше, но все равно мне не нравится.

**Comment by soredake** [comment]
Когда выпилят открытие сайта можно будет задуматься о добавлении в список.

**Comment by The-OP** [comment]
Не выпилят. Но вот например [такой](https://github.com/Robbendebiene/Gesturefy/blob/master/src/lib/background.js#L151) компромиссный вариант (открытие сайта по клику на нотификейшн) меня бы устроил. Надо наверное им пулл-реквест попробовать заслать.

**Comment by The-OP** [comment]
@soredake 
Если время будет - попробуй эти аддоны в качестве более легковесных альтернатив:
https://addons.mozilla.org/en-US/firefox/addon/xstyle/
https://addons.mozilla.org/en-US/firefox/addon/re-style/
Хотелось бы знать, как они в сравнении, с т.з. пользователя Stylus.

**Comment by soredake** [comment]
@The-OP попробую, хоть и теперь я пользуюсь встроенным userChrome.css

**Comment by The-OP** [comment]
Надо же, все-таки выпилили. Добавлю в шапку чуть позже.

**Comment by tanmatra** [comment]
Так и не добавили.
