### ISSUE TITLE
Устаревшие конфиги

### ISSUE THREAD

**Issue by 0okajq** [The-OP/Fox#122]
Привет, чекнул сейчас твои настройки и сверил их со списком устаревших от [ghacks](https://github.com/ghacksuserjs/ghacks-user.js/blob/master/user.js) (в самом низу) и вот что получилось:
`( 499 dupe of 67 ): user_pref("browser.polaris.enabled", false);`
`( 504 dupe of 45 ): user_pref("browser.safebrowsing.gethashURL", "");`
`( 505 dupe of 46 ): user_pref("browser.safebrowsing.malware.reportURL", "");`
`( 506 dupe of 51 ): user_pref("browser.safebrowsing.provider.google.appRepURL", "");`
`( 512 dupe of 48 ): user_pref("browser.safebrowsing.updateURL", "");`
`( 549 dupe of 116 ): user_pref("datareporting.policy.dataSubmissionEnabled.v2", false);`
`( 593 dupe of 166 ): user_pref("dom.disable_window_open_feature.scrollbars", true);`
`( 595 dupe of 278 ): user_pref("dom.push.udp.wakeupEnabled", false);`
`( 597 dupe of 109 ): user_pref("browser.usedOnWindows10.introURL", "");`
`( 607 dupe of 187 ): user_pref("security.ssl3.ecdhe_ecdsa_rc4_128_sha", false);`
`( 608 dupe of 188 ): user_pref("security.ssl3.ecdhe_rsa_rc4_128_sha", false);`
`( 609 dupe of 189 ): user_pref("security.ssl3.rsa_rc4_128_md5", false);`
`( 610 dupe of 190 ): user_pref("security.ssl3.rsa_rc4_128_sha", false);`
`( 612 dupe of 368 ): user_pref("plugins.update.url", "");`
`( 617 dupe of 256 ): user_pref("dom.vr.oculus050.enabled", false);`
`( 619 dupe of 422 ): user_pref("network.http.spdy.enabled.v3-1", false);`
`( 628 dupe of 317 ): user_pref("media.gmp-eme-adobe.enabled", false);`
`( 629 dupe of 316 ): user_pref("media.gmp-eme-adobe.visible", false);`
`( 630 dupe of 318 ): user_pref("media.gmp-eme-adobe.autoupdate", false);`
`( 632 dupe of 261 ): user_pref("dom.telephony.enabled", false);`
`( 642 dupe of 243 ): user_pref("dom.battery.enabled", false);`
`( 644 dupe of 191 ): user_pref("security.tls.unrestricted_rc4_fallback", false);`
`( 651 dupe of 303 ): user_pref("media.getusermedia.screensharing.allow_on_old_platforms", false);`

То есть вышеперечисленное - устаревшее и удалённое

**Comment by The-OP** [comment]
То, чего нет в 52, будет убрано после выпуска 52.2 ESR.

**Comment by dartraiden** [comment]
Ещё имеет смысл удалить `xpinstall.signatures.required` (она не работает) и все, начинающиеся с `loop.` (поскольку Firefox Hello всё).

**Comment by The-OP** [comment]
>xpinstall.signatures.required (она не работает)

Работает (известно где).

Вообще, удаления настроек я стараюсь отслеживать очень тщательно - вплоть до коммита/бага, в котором удалили. Так что не стоит тратить ваше время на помощь в этой области - мне все равно придется все перепроверять.

**Comment by dartraiden** [comment]
>> Работает (известно где).
Только толку от неё, она не починит волшебным образом дополнение, которое завязано на что-нибудь уже выпиленное.

**Comment by The-OP** [comment]
Известно где - это не только в unbranded, но и в ESR. И чинить ничего может быть и не надо - просто неподписанное дополнение поставить, например, свое.

**Comment by The-OP** [comment]
dfb7821
