### ISSUE TITLE
Shield Recipe Client

### ISSUE THREAD

**Issue by The-OP** [The-OP/Fox#123]
> leedoyle replied Jun 14, 2017 • edited

>@The-OP Кстати, я тут ковырялся в about:performance и нашёл ещё один системный аддон, который предназначен по сути для телеметрии. Называется shield recipe.
>https://superuser.com/questions/1205869/what-is-shield-recipe-client
>https://wiki.mozilla.org/Firefox/Shield
>Присутствует как минимум в 53 лисе. В 54 пока не смотрел, но, думаю, тоже есть. Считаю, имеет смысл добавить настройку

>extensions.shield-recipe-client.enabled;false

>в один из первых трех prefs.js
>Я бы закоммитил, но не знаю, в какой из файлов это лучше.
>Возможно, имеет смысл поковырять и остальные настройки, которые находятся по слову shield. Насчёт деинсталляции неуверен. Я нажимал кнопку деинсталлировать в списке about:performance, но не проверял, удалилось ли оно.

>P.S. я до этого ставил TestPilot (потом удалил). Возможно shield включён не у всех юзеров.

(Ссылку на Ungoogled выкинул, ибо она туда случайно попала, как я понял.)

**Comment by The-OP** [comment]
>Присутствует как минимум в 53 лисе.

Проверь лучше еще раз. Ни в about:debugging, ни в папке с системными аддонами (features) я ничего такого не вижу. Да и не должно его там быть, судя по [этому](https://dxr.mozilla.org/mozilla-release/source/browser/extensions/moz.build#16).

**Comment by leedoyle** [comment]
Не имеет смысла проверять, во-первых у меня это точно было, во-вторых я уже накатил 54. 
Присутствие у меня Shield может быть связано с тем, что я ставил Test Pilot и пробовал Tab Center и Containers, ещё ставил Addon Compatibility Reporter.

**Comment by The-OP** [comment]
Смысл имеет, чтобы понимать, что именно происходит. Поставил я тут на 54 Test Pilot, включил в нем все экмприменты, Addon Compatibility Reporter тоже установил - в результате никакого Shield нет.

Может этот профиль, на котором обнаружился Shield, использовался из Nightly?

**Comment by leedoyle** [comment]
Нет, не использовался. 
Думается, практика показывает, что достаточно превентивно дизейблить, а разбираться необязательно. Ты же знаешь, они иногда избирательно включают функции.
https://github.com/mozilla/testpilot-containers Вот тут упоминается Shield так, как будто он с контейнерами в комплекте идёт.

**Comment by The-OP** [comment]
>Серверная часть облачного сервиса открыта и может быть поднята на своих мощностях (применяется Node.js и PostgreSQL).

Ага, вот только адрес сервера там не в префе, а захардкожен.


Ладно, по поводу Shield, как я понял, все обсуждено. Можно закрывать?
