### ISSUE TITLE
ряд поправок и мыслей

### ISSUE THREAD

**Issue by leedoyle** [The-OP/Fox#126]
**1.** Я думаю, можно увеличить модульность шапки за счёт большего соответствия настроек описанию файлов.

Например в первом префе есть отключение:
Predictor
поисковые подсказки
Pageshot
>// Отключает показ нескольких последних созданных закладок в меню закладок. 
(// Отключает интегрированную поддержку проприетарного сервиса закладок Pocket)
`+ настройка отключающая поиск из адресной строки `

Как минимум эти настройки следует убрать во второй преф("настройки отключающие не особо нужную функциональность", если даже не в третий. Или поменять/дополнить описания первого префа.
Правда насчёт покета я лично не уверен, думаю, в СНГ им почти не пользуются, его я бы оставил в первом префе, даже несмотря на то что формально ему во второй. 

**2.** Небольшое расширение комментария настройки
`user_pref("dom.select_events.textcontrols.enabled", false);`
>You may notice that you cannot paste content into forms anymore, that sites may break, or that automatic form filling is not working anymore.

Думаю, можно добавить это в комментарий.

В списке ломающихся от применения настроек сайтов имеет смысл дать ссылки на строчки в файлах prefs.

**3.**
https://github.com/The-OP/Fox/blob/master/prefs/prefs_4.js#L50
пропал в релизной лисе. Появилось ли что вместо него?

**4**  
https://github.com/The-OP/Fox/blob/master/prefs/prefs_4.js#L159

> // Маскировка браузера под версию 38.2 ESR и самую распространённую платформу. Не забываем обновлять

Стоит обновить. Уже две ESR сменилось с тех пор.

**5** 
Предлагаю добавить в шапку информацию о восстановлении изменённого в худшую сторону интерфейса загрузок в FF 54:
https://www.ghacks.net/2017/06/17/restore-download-information-in-firefox/

**Comment by The-OP** [comment]
(В следующий раз не надо пихать в один тикет кучу вопросов и предложений - очень неудобно обсуждать.)

1. По поводу этого отвечу позже.

2. Откуда этот комментарий?

>В списке ломающихся от применения настроек сайтов имеет смысл дать ссылки на строчки в файлах prefs.

А потом не забывать их править. Зачем?

3. Не пропал, его просто не видно.

4. Там еще и билд при каждом минорном обновлении ESR меняется. Да я вот думаю, стоит ли? В качестве примера как через конфиг можно менять заголовки/свойства - сгодится, а реально это делать малополезно. Но если тебе очень хочется, можешь поставить на Винду последний ESR, глянуть через Developer Tools нужные window.navigator.* и заслать пулл-реквест.

5. Принимается: 6e1716f

**Comment by The-OP** [comment]
1. Перенес Pocket, Pageshot и showRecentlyBookmarked во вторую категорию.

**Comment by andorank** [comment]
Извини что пишу в этот тикет, мно мне нужен `keyword.enabled -> true`, т.к. я ищу через адресную строку, особбено после включения, `browser.urlbar.oneOffSearches` так что перенеси его хотя бы во вторую категорию.

**Comment by The-OP** [comment]
>перенеси его хотя бы во вторую категорию

Нет.

>я ищу через адресную строку

Ищи при помощи префиксов. Ну или или локально себе включай `keyword.enabled`, если уж так хочется.

**Comment by Aonavan** [comment]
@The-OP 
> Нет. 

Почему нет? Попадает под категорию нужной некоторым функциональностью.

> Ищи при помощи префиксов.  

Не очень удобно,  а должно быть наоборот, исходя из описания настроек в первой категории.

> Ну или или локально себе включай keyword.enabled, если уж так хочется.

Хочется чтобы удалённо данный параметр был занесён в третью категорию.

Тоже самое относится к парамтрам обновления браузера из второй категории, место ей в третьей.

**Comment by The-OP** [comment]
>Почему нет?

Потому что должно работать по принципу наименьшего удивления. Если пользователь пишет в адресную строку без префикса - он имеет в виду адрес. И браузеру не надо лезть в поисковик без четкого указания от пользователя.

>парамтрам обновления браузера из второй категории, место ей в третьей

Вот это, пожалуй, так. Перенесу как-нибудь.

>Третья категория и так очень маленькая по сравнению с остальными, так что не зазорно её заполнять.

Категории заполняются не по принципу равномерности.

**Comment by Aonavan** [comment]
@The-OP А через`browser.search.update` насколько вообще критичные обновления? Может тоже перенести стоит?

**Comment by The-OP** [comment]
>через browser.search.update насколько вообще критичные обновления?

Ну давай подумаем. Что может там обновиться? Query-параметр через который запрос передают что ли? Весьма маловероятно. Дефолтный поисковик для региона, с которым у Mozilla контракт на продвижение? Это нас не колышет.

**Comment by Aonavan** [comment]
@The-OP Понятно. А как насчёт переноса совпадающих с дефолтом настройки в prefs_0.js? Я не думаю что `browser.send_pings` когда-либо включат, да и много таких настроек там.

**Comment by The-OP** [comment]
Какой в этом смысл?

**Comment by Aonavan** [comment]
На радость тем кто предпочитает недобдеть, например: https://github.com/The-OP/Fox/issues/108.

**Comment by The-OP** [comment]
>переноса совпадающих с дефолтом настройки в prefs_0.js

>Есть ли смысл в изменении дополнительных параметров, если основной (логическая переменная) уже переведён в "false"?

Одно с другим вообще никак не связано. Поясни подробнее, чего ты добиваешься.

**Comment by Aonavan** [comment]
@The-OP А, я неправильно понял. Я про то что такие настройки как `browser.send_pings` никогда не включат по умолчанию, как я думаю, и таких настроек там много, которые перемешаны с настройками которые что-то отключают, так что их приходится отсеивать когда перебираешь настройки.

**Comment by The-OP** [comment]
>их приходится отсеивать когда перебираешь настройки

Зачем?

**Comment by Aonavan** [comment]
@the-op Потому что они ничего не делают, значения такие же стоят по умолчанию.

**Comment by The-OP** [comment]
Ну и что? Тебе это как-то жить мешает? Или ты их там вручную по одной переключаешь?

В любом случае, никакого "prefs_0" не будет. В одной версии настройка по умолчанию выключена, в следующей - включена. Таскать их туда-сюда - это бесполезная ерунда какая-то.

**Comment by The-OP** [comment]
Это можно закрывать, как я понимаю.
