### ISSUE TITLE
Чёрный список авторов аддонов

### ISSUE THREAD

**Issue by Aonavan** [The-OP/Fox#127]
Данный автор продал расширение Youtube Plus в хромсторе нехорошим личностям:
https://github.com/ParticleCore/Particle/issues/528
Так что доверия к нему и к его аддонам на АМО теперь никакого. Может имеет смысл добавить в тот же серый список подобных авторов?

**Comment by Aonavan** [comment]
Прости, заметил подобное обсуждение, лучше прододить его там: https://github.com/The-OP/Fox/issues/40

**Comment by The-OP** [comment]
Я почитал ссылку - не думаю, что стоит. Целиком автора блэклистить имеет смысл, если у него в нескольких аддонах зонды, и он по этому поводу не раскаивается. Тем более, там расширение не для Firefox вообще.

**Comment by Aonavan** [comment]
@The-OP Кстати, теперь почти каждый аддон будет открывать свой официальный сайт при установке и каждом обновлении аддона. Потому что в webextensions нет никаких настроек для отключения этой навязчивой рекламы, т.к. нет доступа к about:config.
