### ISSUE TITLE
Добавление аддона MixedContentHunter 

### ISSUE THREAD

**Issue by Aonavan** [The-OP/Fox#129]
Полезный аддон, например заставляет грузиться картинки через https если они это по умолчанию не делают,  когда настройка `security.mixed_content.block_display_content` просто их не грузит, из-за чего некоторые сайты ломаются от этого, для чего чёрный список есть.
https://addons.mozilla.org/en-US/firefox/addon/mixedcontenthunter

**Comment by The-OP** [comment]
6846a32
