### ISSUE TITLE
Стиль скрывающий попап с запросом FlashPlugin

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#13]
https://github.com/firefoxForUser/esr38config/blob/master/userChrome.css

**Comment by firefoxForUser** [comment]
Другого способа отключить это не знаю.

**Comment by The-OP** [comment]
plugins.notifyMissingFlash -> false уже не работает?

**Comment by firefoxForUser** [comment]
Не работает. При установленном значении "клик для воспроизведения" для флэш плагина данный попап выскакивает даже тут, на github. Читал где-то, что так сделанно только для FlashPlugin из всех плагинов.

**Comment by The-OP** [comment]
А, ты про предложение включить Флэш на данной странице, а не установить. И что ты хочешь, чтоб я с этим стилем сделал? В шапке ссылку дать? Тогда лучше на userstyles.org залить.

**Comment by firefoxForUser** [comment]
Ну список настроек у тебя хороший, поэтому и предлагаю. Можно вкомитить файл userChrome.css и предлагать тем кто хочет просто кинуть его в соответствующий каталог профиля, тогда стили применятся. А кто захочет и в Stylish вставит.

**Comment by The-OP** [comment]
Я подумал и решил не делать "официальный" userChrome.css, ибо интерфейс - большая вкусовщина, и каких-либо универсальных твиков для него, подходящих всем, практически нет. Что касается Флэша - на мой взгляд, его пользователям жизнь облегчать не нужно, а даже наоборот. Это один из самых кривых и дырявых кусков софта и чем раньше он будет предан забвению, тем лучше.
