### ISSUE TITLE
Автономное хранилище

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#131]
При запуске некоторых сайтов в адресной строке появляется запрос от автономного хранилища на разрешение сохранения каких=то данных на компьютере (правда, почему-то не при клике по значку не открывается панель автономного хранилища; может какой параметр запрещает его открытие?).
Занести заранее свой список сайтов всё так же невозможно? Или хотя бы поставить этот в состояние "Запретить всем"?

**Comment by The-OP** [comment]
>Занести заранее свой список сайтов всё так же невозможно?

Уже отвечал в #102

>Или хотя бы поставить этот в состояние "Запретить всем"?

`browser.cache.offline.enable` ?

**Comment by AlxMxlA** [comment]
>> browser.cache.offline.enable ?

И так стоит false.

**Comment by The-OP** [comment]
Тогда давай полный список steps to reproduce.

**Comment by The-OP** [comment]
Ответа нет - значит закрываю.
