### ISSUE TITLE
Папка Закладок в новом окне

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#134]
С применёнными в конфигурационном файле всех пяти категорий настроек не открываются в новом окне папки Закладок.

**Comment by The-OP** [comment]
>всех пяти категорий настроек

Не надо так делать.

**Comment by AlxMxlA** [comment]
>> Не надо так делать.

Ну это то же правильно. :)
Хотя, в целом, почти всё, так или иначе при минимальных изменениях в конфигах, работает.
Так а как разрешить открытие Закладок в новом окне?

**Comment by The-OP** [comment]
>не открываются в новом окне папки Закладок

Я не понимаю, что это означает.

**Comment by AlxMxlA** [comment]
Правой кнопкой мыши по иконке Закладок на Панели инструментов->Выбор любой папки с закладками (по умолчанию их нет; создаются пользователем)->Открыть в новом окне.
Должно открыться новое окно а в нём во вкладках все закладки, хранившиеся в этой папке.

**Comment by The-OP** [comment]
>Открыть в новом окне.

Это Open All in Tabs что ли? Так оно и не создает новое окно. И у меня работает вроде.

**Comment by AlxMxlA** [comment]
>> Open All in Tabs что ли?

Нет - Open all in new window.
Open All in Tabs и у меня работает

**Comment by The-OP** [comment]
>Open all in new window

Такого пункта нет в Firefox без аддонов.

**Comment by The-OP** [comment]
Можно закрывать, насколько я понимаю.
