### ISSUE TITLE
Сортировка по первым словам настройки

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#14]
Вопрос удобства. IMHO удобнее читать, если отсортировано по первым словам названия настройки

Сеть:
network.bla1
network.bla2

Поведение:
browser.bla3
browser.bla4

Плагины:
plugin.bla5

**Comment by firefoxForUser** [comment]
Как вариант можно вынести в отдельные файлы.

**Comment by The-OP** [comment]
Я их сортировал почти всегда по принципу "сначала - менее ломающие", даже внтури одного файла. Поэтому отключение правеки обновлений, например, в самом конце второго.
