### ISSUE TITLE
GreaseMonkey is ported to WebExtension and has new asynchronious API.

### ISSUE THREAD

**Issue by KOLANICH** [The-OP/Fox#140]

**Comment by The-OP** [comment]
Да, видел. И что ты хочешь, чтобы я с этим сделал?

**Comment by KOLANICH** [comment]
список пофиксил.

**Comment by The-OP** [comment]
А, это. Так на AMO 4.0 релиза еще нет. Появится - пофикшу.

**Comment by KOLANICH** [comment]
>Так на AMO 4.0 релиза еще нет. 

Есть экспериментальный. Он хотя-бы работает на esr, в отличие от последнего 3го.

**Comment by The-OP** [comment]
Это же альфа. Странно, у меня третий работает вроде на ESR. А четвертый и прочие WE на ESR как раз лучше не ставить из-за нерешенных проблем с CSP.

**Comment by KOLANICH** [comment]
>А четвертый и прочие WE на ESR как раз лучше не ставить из-за нерешенных проблем с CSP.

И что там за проблемы?

**Comment by The-OP** [comment]
Вот этот баг: https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by KOLANICH** [comment]
Спасибо.

**Comment by The-OP** [comment]
1fd911f
