### ISSUE TITLE
Что с HTTPS Everywhere?

### ISSUE THREAD

**Issue by devarped** [The-OP/Fox#141]
Насколько я помню, до ситуации с переходом WebExtensions в HTTPS Everywhere был анальный зонд SSL Observatory, отправлявший список SSL-сертификатов посещаемых сайтов куда-то в недра EFF.
>If you turn on this feature, it will send anonymous copies of certificates for HTTPS websites to EFF's SSL Observatory database
https://www.eff.org/deeplinks/2012/02/https-everywhere-decentralized-ssl-observatory

Впрочем, тогда имелась успокаивающая галочка выключения этого зонда. Но с переходом на WebExt она пропала, судя по всему, став принудительной. 

Собственно, вопрос: были ли какие-нибудь вопросы разработчикам, пруфы или пояснения насчёт этого весьма подозрительного поведения?

Если опасения подтверждены, то стоит добавить аддон в серый список. В качестве альтернативы имеется [Smart HTTPS](https://addons.mozilla.org/ru/firefox/addon/smart-https-revived/), который, впрочем, работает несколько по-другому (проверяет наличие HTTPS у каждого посещаемого сайта вместо редиректа для сайтов из списка), из-за чего ломается на некоторых сайтах (например, exhentai.org).

**Comment by The-OP** [comment]
>тогда имелась успокаивающая галочка выключения

Не выключения, а включения.

>судя по всему, став принудительной

Откуда такая информация?

Посмотрел сейчас исходники актуальной версии - ничего подозрительного не вижу.

**Comment by devarped** [comment]
>Не выключения, а включения.

Верно. Просто включена она была по дефолту.
>Откуда такая информация?

Просто небольшой приступ паранойи. 
Во всяком случае, я сейчас просмотрел результаты поиска в репозитории по "observatory", нашёл лишь пару скриптов в /utils/. Похоже, ситуация действительно изменилась, но осторожным быть не помешает.

**Comment by The-OP** [comment]
>включена она была по дефолту

Нет, он спрашивал, включить или нет при первом запуске.

>Похоже, ситуация действительно изменилась

В WE вообще нет API, чтобы достучаться до сертификатов, насколько я понимаю.
