### ISSUE TITLE
Переформатирование раздела аддоны и продвинутые аддоны в связи с релизом Firefox 57

### ISSUE THREAD

**Issue by leedoyle** [The-OP/Fox#142]
На данный момент там свалены в кучу аддоны, которые работают на  **релизной** лисе и которые на ней не работают.
Предлагаю обсудить, из чего мы исходим - что адресаты шапки пользуются (или должны пользоваться) Firefox ESR или что они в большинстве пользуются Firefox 57+.
И в первом, и во втором случае в начале шапки стоит разместить дисклеймер, чтобы люди понимали, где и какую информацию им искать.

Также предлагаю подумать о перечислении сначала WE аддонов, а уже потом остальных с соответствующими подзаголовками. Возможны и другие решения: например, добавить ещё один .md файл специально для аддонов под Firefox 57 (при этом не меняя того, как представлена информация о WE аддонах в нынешней версии шапки).

**Comment by The-OP** [comment]
Думал об этом, но мне не нравится появляющееся дублирование аддонов, у которых есть и старая, и новая версии. Пускай уж так висит, пока 52 ESR существует.

**Comment by ficofabrid** [comment]
@The-OP почему некоторые аддоны помечаяются с WE и E10S одновременно, когда WE и так E10S по умолчанию.

**Comment by The-OP** [comment]
Там же написано:

> WE, E10S - есть как Web Extension, так и старая версия расширения, которую можно использовать на Firefox 52 ESR.

**Comment by leedoyle** [comment]
Основная проблема тут в том, что приходят новые люди, поставившие или обновившиеся до Firefox 57, которые вообще слов вроде e10s не знают, открывают шапку... и что? Пойдут пытаться ставить CookieMonster на 57 лису? А дальше?

**Comment by The-OP** [comment]
>приходят новые люди, поставившие [...] Firefox 57 [...], открывают шапку

Это ты хорошо пошутил.

>А дальше?

А дальше AMO не даст поставить не туда.

>Пояснение выше не решает проблему

А какое решает?

>не-e10s расширения могут существенно тормозить браузер при включенном электролизе (или вообще не работать)

Так они его и вырубят. Ну а если кто форсирует, он ССЗБ и (видимо) знает, что делает.

**Comment by The-OP** [comment]
Поскольку никаких новых идей не поступило, можно закрывать, как я понимаю.
