### ISSUE TITLE
PDF.js

### ISSUE THREAD

**Issue by The-OP** [The-OP/Fox#143]
После введения сэндбоксинга контент-процесса, PDF.js по-моему становится более безопасным чем 3rd-party читалки PDF, в которых нет никакого запрета на чтение файлов юзера.

Так что есть мысль включить его обратно для большинства юзеров, перенеся отключение из второй категории в четвертую. Ну а те, кто считают, что могут организовать себе более секъюрный сетап, пускай берут отключение из четвертой категории.

Хотя, с другой стороны, PDF.js может жрать память и вызывать нестабильность браузера: [1](https://bugzilla.mozilla.org/show_bug.cgi?id=1417668), [2](https://bugzilla.mozilla.org/show_bug.cgi?id=1374945), [etc](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=pdf).

Контрибуторы, что думаете по этому поводу? @dartraiden @KOLANICH @leedoyle @soredake

**Comment by KOLANICH** [comment]
>После введения сэндбоксинга контент-процесса, PDF.js по-моему становится более безопасным чем 3rd-party читалки PDF

По-моему уже сам факт того, что он написан на memory-safe языке вместо c++, делает его безопаснее. Т.е. даже без сендбоксинга исчезает целый класс уязвимостей. Зато появляется новый класс, связанный с `eval` и `new Function` , `setTimeout/setInterval` с текстовым параметром вместо функции (давно пора выпилить, насрав на совместимость с поделиями профнепригодных), всякими атрибутами `on<event>` (давно пора выпилить, насрав на совместимость с поделиями профнепригодных), `<a href="javascript:"> (оставить только для букмарклетов и пользовательского ввода в адресную строку) и отсутствием фильтрации данных (`document.write`, `innerHTML`), и, что по-моему самое опасное, - переопределением методов в привилегированном контексте из непривелегированного (ИМХО должно решаться на уровне движка javascript назначением каждому объекту уровня привилегий, распространением уровня при операциях запрограммированным путём, проверках при вызовах методов и бросанием ошибок), но это хотя-бы можно контролировать: все эти API давно известны.

>Так что есть мысль включить его обратно для большинства юзеров, перенеся отключение из второй категории в четвертую.

полностью за

>Хотя, с другой стороны, PDF.js может жрать память и вызывать нестабильность браузера

у меня и foxit на некоторых документах жрёт дофига памяти.

Хотя лично я использую foxit, так как он намного быстрее чего-либо другого, включая эдоубовский. И ещё в pdf.js есть проблемы с рендерингом некоторых документов.

**Comment by dartraiden** [comment]
Солидарен с предыдущим комментарием, хотя и пользуюсь сторонним приложением, вообще ничего не открывая в браузере, кроме изображений.

**Comment by The-OP** [comment]
cae3ccb
