### ISSUE TITLE
extensions.enabledScopes

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#144]
Имеет смысл добавить в конфиг.

Описание:
https://www.ghacks.net/2013/02/20/how-to-block-new-add-on-or-plugin-installations-in-firefox/

> The preference extensions.enabledScopes can be assigned the sum of the following values or 0 to disable it.
> 
>     0 disables it
>     1 will block installations of add-ons from the user's profile directory.
>     2 will block installations referenced by the current user's Registry entry or add-ons that are in the user's extensions directory.
>     4 will block extensions that are in the extension directory of the Firefox installation.
>     8 will block any add-on from being loaded in Firefox if it is referenced by System Registry entries, or add-ons that are in the system's extension directory if it exists.

`8` выглядит наиболее оптимальным значением

**Comment by The-OP** [comment]
Что-то там не то написано, судя по [1](https://dxr.mozilla.org/mozilla-release/rev/d47195ec274d20ed53ff0eb0ea2f72f7168f6ad9/toolkit/mozapps/extensions/internal/XPIProvider.jsm#2106) и [2](https://dxr.mozilla.org/mozilla-release/rev/d47195ec274d20ed53ff0eb0ea2f72f7168f6ad9/toolkit/mozapps/extensions/AddonManager.jsm#3413). Наоборот надо 1 ставить, чтобы только из профиля грузились. И это не отключает системные аддоны, так что я не понял, в чем смысл.

**Comment by dartraiden** [comment]
Это отключает third-party дополнения. Всякие антивирусы и прочий софт, который через реестр прописывает свои дополнения.

**Comment by The-OP** [comment]
Так ты хочешь чтобы только из профиля грузились? Но если кто-то себе поставил такой софт, ему видимо нужны эти дополнения.

**Comment by dartraiden** [comment]
Не факт, например, Касперский суёт туда свои дополнения и автоматически игнорирует настройку "автоматически активировать дополнение в браузере"

**Comment by The-OP** [comment]
Ну так что, 1 ставить? И в какую категорию лучше поместить?

**Comment by dartraiden** [comment]
Я думаю - в prefs_3.js. Да, 1.

**Comment by The-OP** [comment]
Так, стоп. А вот это правда или нет?

>This is doing using the extensions.enabledScopes preference which you can only add via an autoconfig file.

Протестировать можешь, работает ли из user.js?

**Comment by dartraiden** [comment]
Работает, как при ручном создании, так и через user.js

**Comment by The-OP** [comment]
4eb1f43
