### ISSUE TITLE
аддоны, установленные в браузер сторонними...

### ISSUE THREAD

**Issue by sciamano** [The-OP/Fox#145]
https://github.com/The-OP/Fox/blob/ac3f3196d5c896cbb0b06af40c464082a36b7799/prefs/prefs_3.js#L121

добавить бы примечание, что в линукс (как минимим debian-based) системах эта опция отключает все расширения установленные через системный менеджер софта (apt-get xul-ext-ublock-origin и т.п.)

**Comment by The-OP** [comment]
Добавить не проблема, только uBlock в Дебиане все равно годовалой давности.

7a927d0
