### ISSUE TITLE
о кэше

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#15]
user_pref("browser.cache.disk.capacity", 0); - такая настройка стоит в портативной версии Portable Apps. То есть кэш не отключается, а его размер ставится в 0. Где-то читал, что это связанно с каким-то багом и лучше именно ставить в 0, а не  отключать. У вас же он сначала отключается, а потом ставится в 0, что как бы приводит к игнорированию настройки установленной в 0.

**Comment by The-OP** [comment]
>Где-то читал, что это связанно с каким-то багом и лучше именно ставить в 0, а не отключать

Где? Использую с отключенным уже некоторое время - багов не замечал.

**Comment by firefoxForUser** [comment]
К сожалению этого не вспомню.

Да и в TorBrowser эта настройка есть, так что ошибся:

As an additional defense-in-depth measure, we set the following preferences: , browser.cache.disk.enable, browser.cache.offline.enable, dom.indexedDB.enabled, network.cookie.lifetimePolicy, signon.rememberSignons, browser.formfill.enable, browser.download.manager.retention, browser.sessionstore.privacy_level, and network.cookie.lifetimePolicy. Many of these preferences are likely redundant with browser.privatebrowsing.autostart, but we have not done the auditing work to ensure that yet. 

https://www.torproject.org/projects/torbrowser/design/
