### ISSUE TITLE
Некоторые опции из "братских" проектов

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#17]
[отсюда](https://github.com/amq/firefox-debloat):
media.gmp-eme-adobe.enabled = false
EME уже отключены полностью в текущей версии наших настроек, но как "контрольный выстрел" — пойдёт.

[отсюда](https://github.com/TheCreeper/PrivacyFox):
network.websocket.enabled = false
вебсокеты в ряде случаев отправляют запросы DNS не через прокси, а напрямую ([пруф];(https://blog.torproject.org/blog/firefox-security-bug-proxy-bypass-current-tbbs))
было бы интересно выяснить, лечится ли это включением network.proxy.socks_remote_dns, поскольку идея отключать вебсокеты мне не очень нравится.

privacy.trackingprotection.enabled = false
раз уж отключаем SafeBrowsing, возможно, стоит отключить и это, поскольку используются те же самые апи ([источник](https://github.com/amq/firefox-debloat/pull/2#issuecomment-115728580)). Если это правда, то в лучшем случае tracking protection просто не будет работать без них, а в худшем - долбиться в гугл. В любом случае, эту работу может (и должен) делать uBlock.

**Comment by The-OP** [comment]
Надо же, оказывается порядочно таких проектов. Хоть собираться и писать петицию в Мозиллу, чтоб сделали одну кнопку "отключить все зонды".

> media.gmp-eme-adobe.enabled = false

Сделано.

>вебсокеты в ряде случаев отправляют запросы DNS не через прокси, а напрямую

Пофиксили: https://bugzilla.mozilla.org/show_bug.cgi?id=751465

>privacy.trackingprotection.enabled = false

А оно пока везде выключено по умолчанию. Но пускай будет на будущее.

**Comment by dartraiden** [comment]
Вдогонку — privacy.trackingprotection.pbmode.enabled = false
Из свеженького 39-го. tracking protection в приватном режиме

**Comment by The-OP** [comment]
Добавил.
