### ISSUE TITLE
Опции от коллег

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#18]
https://github.com/pyllyukko/user.js

**Comment by The-OP** [comment]
Бегло посмотрел - вроде неплохо. Но там довольно много всего, надо разбираться, так что буду подтягивать сюда постепенно.

**Comment by fenque** [comment]
http://thesimplecomputer.info/tscs-firefox-tweak-guide
https://www.privacytools.io/#about_config
Думаю эти три ссылки стоит добавить в раздел "Интересные ссылки".

**Comment by The-OP** [comment]
А где третья? Посмотрел две - из тамошних конфигов все полезное есть и здесь (а кое-чего вредного наоборот нет), так что интерес представляют скорее ссылки, которые находятся по тем ссылкам.

**Comment by The-OP** [comment]
Если под третьей имелся в виду репозиторий @pyllyukko, то туда я не очень хочу давать ссылку, потому что я не согласен с некоторыми из его решений (например, оставлением Safebrowsing), равно как и с архитектурой "один конфиг на все случаи жизни" (считаю, что должны быть профили для разных целей с разными комбинациями настроек из категорий 1-4). Да и подтянуть оттуда сюда осталось немного (а все важное уже подтянуто).

**Comment by fenque** [comment]
@The-OP ты не согласен, кто-то будет согласен, пусть построят свое мнение/конфиг исходя из всех этих ссылок.

**Comment by The-OP** [comment]
>пусть построят свое мнение/конфиг исходя из всех этих ссылок.

Ну допустим (касательно репозитория коллег). Но насчет "всех" - это перебор. Подобных последним двум ссылок сотни. Для того и существует этот репозиторий, чтоб не приходилось по всем ним выискивать настройки, которые еще часто неполные, неверные или устаревшие.

**Comment by The-OP** [comment]
bd074dc

**Comment by dartraiden** [comment]
вот ещё
http://www.ghacks.net/2015/08/18/a-comprehensive-list-of-firefox-privacy-and-security-settings/

**Comment by The-OP** [comment]
@dartraiden Cсылку на них вписать или что?

**Comment by dartraiden** [comment]
В том смысле, вдруг там в списке что-то доселе неизвестное найдётся, что можно утащить к нам.

**Comment by The-OP** [comment]
@dartraiden, да, некоторые полезные вещи там есть. Ты не против, если я это перенесу в отдельный issue, а комментарии здесь удалю?

**Comment by dartraiden** [comment]
Конечно
