### ISSUE TITLE
Дополнения для удобства настройки приватности

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#19]
Вот. Думаю кстати на его базе можно и своё сделать.

Privacy Settings
https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/

Есть ещё, но там ориентация не на приватность.
Configuration Mania
https://addons.mozilla.org/en-us/firefox/addon/configuration-mania-4420

**Comment by The-OP** [comment]
Так все из него уже есть здесь в prefs_1/2.

**Comment by firefoxForUser** [comment]
Имелся ввиду пример кода, который можно использовать, как пример для написания своего. Да и появление подобных тоже показатель. В новостях на opennet.ru пишут, что Mozilla собирается сделать нечто вроде кнопки "отключить все следилки" для работы с Tor. В общем следим за развитием.

**Comment by The-OP** [comment]
Можно, но смысл подобного от меня ускользает. Тыкать кнопки в расширении ничуть не проще чем закинуть настройки в user.js, а возни с расширениями намного больше - там даже preliminary review чуть ли не месяц. Да еще и этот маразм с подписью, так что даже у себя не захостишь без получения одобрения с AMO.
