### ISSUE TITLE
2 строки склеились

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#2]
prefs_2.js:
user_pref("media.gmp-gmpopenh264.autoupdatemedia.gmp-gmpopenh264.enabled", false);

должно быть:
user_pref("media.gmp-gmpopenh264.autoupdate", false);
user_pref("media.gmp-gmpopenh264.enabled", false);

**Comment by The-OP** [comment]
Пофиксил: e8198b7002aca2dcd95b558209341690223c81bb
