### ISSUE TITLE
Генеральная уборка

### ISSUE THREAD

**Issue by The-OP** [The-OP/Fox#20]
Когда дропнут поддержку Fx31 (после выпуска Fx40), убрать все устаревшие опции, не имеющие эффекта в Fx38.

**Comment by The-OP** [comment]
Вместе с Fx40 выйдет Fx38.0.2esr, и можно будет убрать единственное разветвление между настройками для Fx38 и Fx39+.

>[Firefox 39 and Firefox ESR 38.0.2 will include changes that will increase the minimum strength of keys to 1024 bits.](https://addons.mozilla.org/en-US/firefox/addon/disable-dhe/)

**Comment by The-OP** [comment]
На AMO выше опечатка - готовящееся обновление 38 ESR называется 38.2.0. Проверил [кандидат](https://ftp.mozilla.org/pub/mozilla.org/firefox/candidates/38.2.0esr-candidates/build2/) - к Logjam он неуязвим.

**Comment by stepshal** [comment]
Пришло время очередной уборки.

**Comment by The-OP** [comment]
Да, я в курсе.
