### ISSUE TITLE
Немного о стилях

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#21]
Я не ярый фанат "исправления" стилей. Но хочу внести ясность в тему. Не считая статьи о шрифтах в вашем списке ссылок, существуют и другие хаки. Как пример можно посмотреть на банальную панель поиска по странице (вызываемую по ctrl + F). На том же whoer.net можно удобно наблюдать, как изменяются показатели размера окна при её закрытии/открытии. Фикситься это довольно просто, ставим position:fixed и задаем положение на странице, так и панель будет видна и её открытие/закрытие не будет видно скриптам. Из минусов: некоторые дополнения или пользовательские стили/скрипты изменяющие панель поиска могут поломаться, да и положение кнопочки закрытия поправить надо. Это просто маленький пример, ничего больше.

Понятно, что мелочь. Но думаю можно написать стиль, который например блокирует изменение изображения курсора на некоторых сайтах и т.д. То есть это не просто рюшечки.

**Comment by The-OP** [comment]
>Фикситься это довольно просто

Ну да - спуфингом размеров окна в Random Agent Spoofer. Все остальное было бы ненадежными полумерами - все равно у разных браузеров разные размеры viewport, даже при одинаковом размере окна.

Касательно остального - я что-то вообще не понял, к чему это. Что ты предлагаешь?

**Comment by firefoxForUser** [comment]
Random Agent Spoofer это дополнение, а как показывает практика забрашивание дополнений очень частое явление. То есть иметь средство, как настройки в about:config, которое не зависит от сторонних разработчиков - это хорошо. Понятно, что мой пример не пофиксит всё, но это хоть что-то. Как те же настройки в about:config, как можно видеть на странице https://www.torproject.org/projects/torbrowser/design/ сколько настройки не меняй, а без патча самого кода анонимности не будет. Тогда и список настроек в about:config смысл теряет?

Я не знаю, что предложить. Это была лишь заметка о том, что стилями можно кое-что фиксить в плане приватности. Собирать на этой странице только ссылки, дополнения и настройки или ещё и стили, а может и даже патчи - решать вам.

**Comment by The-OP** [comment]
Поскольку теперь есть раздел для скриптов, пускай будет и для стилей.
