### ISSUE TITLE
Захардкоженный курсор в FF-39

### ISSUE THREAD

**Issue by deterenkelt** [The-OP/Fox#22]
С апдейтом вылезло это чудо. Не знаешь как убрать?
А, да, это на линуксе.

**Comment by The-OP** [comment]
Issues шапки предназначены, как ни странно, для обсуждения улучшений шапки. С остальными вопросами - в тред.

**Comment by deterenkelt** [comment]
Спасибо, обойдусь.

**Comment by deterenkelt** [comment]
Прилетел с adwaita-icon-theme.
