### ISSUE TITLE
Исчезновение кнопки "развернуть на весь экран" в Youtube-роликах

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#24]
// Отключает попытки страниц развернуть себя на весь экран.
// https://developer.mozilla.org/en-US/docs/DOM/Using_fullscreen_mode
user_pref("full-screen-api.enabled", false);
user_pref("full-screen-api.pointer-lock.enabled", false);

думаю, стоит сделать примечание к этим опциям

**Comment by The-OP** [comment]
02ab956
