### ISSUE TITLE
Поддержка Beta, Aurora и Nightly

### ISSUE THREAD

**Issue by The-OP** [The-OP/Fox#27]
Сейчас у нас в разделе настроек поддерживаются релизы Firefox. Для эксперимента я добавил поддержку беты 40, и обнаружил, что новые настройки могут появляться или удаляться даже между разными выпусками бет (40b3 -> 40b6 -> 40b7 -> 40b9). А беты могут выходить с частотой раз в четыре дня. Учитывая подобную изменчивость, целесообразно ли пытаться поддерживать Aurora и Nightly? Ведь следует не просто на автомате отключать все новое, а хотя бы поверхностно смотреть, как оно там работает, и тестировать, не отваливается ли что-то от отключения.

**Comment by The-OP** [comment]
@fenque, каким образом ты ищешь изменения в Aurora? У меня есть парочка самописных костылей для показа разницы в настройках, могу поделиться, если надо.

**Comment by fenque** [comment]
Либо сам натыкаюсь на то что нужно отключить, это штуки типо pocket, hello, проверка подписи дополнений в найтли версии, иногда отсюда http://www.ghacks.net/category/firefox/. А костыли выкладывай, пусть и мне пользу приносят.

**Comment by The-OP** [comment]
Залил в tools.

**Comment by fenque** [comment]
Вот параметр очень нужный, думаю ты придумаешь куда его запилить 
```
// Отключает обязательную проверку наличия подписи у аддона, без которой он не даст установить его.
user_pref("xpinstall.signatures.required", false);

```

**Comment by The-OP** [comment]
Да, я мельком посмотрел 41.0b1-candidate1 - вроде работы там немного, так что вероятно сегодня запилю.

**Comment by The-OP** [comment]
Кстати, некоторые настройки, которые были включены пока 41 был Авророй,  в 41.0b1 уже выключены. А некоторые вообще выпилены (может на 42 оставили). Вообще не понимаю, как можно работать с Авророй.

**Comment by Aonavan** [comment]
@The-OP Как насчёт запилить поддержку беты? Авроры больше нет, ghacks поддержку имеет.

**Comment by The-OP** [comment]
>Как насчёт запилить поддержку беты?

Никак.

>ghacks поддержку имеет

Значит либо у их времени свободного хватает, либо контрибуторов больше. Флаг им в руки, короче.
