### ISSUE TITLE
Годный аддон ...

### ISSUE THREAD

**Issue by KOLANICH** [The-OP/Fox#28]
... был когда-то. Но наверное его можно допилить.

https://github.com/Infocatcher/ArchView/

**Comment by The-OP** [comment]
Ты мне его предлагаешь допилить что ли? Я конечно польщен, но не осилю.

**Comment by KOLANICH** [comment]
Не, предлагаю зафолловить, а когда допилят - добавить в список.

**Comment by KOLANICH** [comment]
https://github.com/sibiantony/ssleuth
