### ISSUE TITLE
Уточнение и дополнение информации из приложения к шапке

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#3]
Раздел "Фингерпринтинг":
предлагаю добавить сервис [AmIUnique?](https://amiunique.org/), впечатляющий [список](https://amiunique.org/faq) отслеживаемых параметров. И [whoer.net](http://whoer.net/)

Раздел "Аддоны":

Clean Links не работает на yandex.ru (ссылка копируется с говном), ломает yandex.com (делает битые ссылки). Пока, единственный вариант - внести яндекс в список исключений, а для яндекса задействовать [Google search link fix(https://addons.mozilla.org/firefox/addon/google-search-link-fix/).

RefControl: "можно рубить только рефереры при переходе на другой домен (Block (3rd party)), оставляя внутридоменные, что просто, эффективно для 99% случаев и не ломает так много сайтов как полный запрет" - аналогичный эффект дает опция network.http.referer.XOriginPolicy = 1 ([пруф](https://addons.mozilla.org/ru/firefox/addon/smart-referer/reviews/570470/) без необходимости таскать лишний аддон

В качестве альтернативы RequestPolicy и Policeman можно добавить [uMatrix](https://github.com/gorhill/uMatrix/releases) (от автора uBlock Origin)

Privacy Badger ещё откровенно сыроват, блокирует он меньше, чем Ghostery ибо встроенной базы трекеров не имеет, а самообучалка действует по принципу "лучше недоблокировать, если не уверен, чем переблокировать". В качестве альтернативы Ghostery есть [Discoonect](https://addons.mozilla.org/ru/firefox/addon/disconnect/), хотя эта контора основана выходцем из Гугла, что как бэ намекает.

HTTPS Everywhere уже [вернулось](https://addons.mozilla.org/en-us/firefox/addon/https-everywhere/) на AMO (хотя, поиском пока не ищется). Видимо, в преддверии грядущего запрета на установку неподписанных аддонов.

В качестве аналога User Agent Switcher можно посоветовать [UAControl](https://addons.mozilla.org/ru/firefox/addon/uacontrol/), который гибче (как RefControl, только для юзерагента, можно создавать исключения и отдельные правила для сайтов). Но он подделывает лишь юзерагент из HTTP-заголовка, но не отдаваемый средствами JS, поэтому, требует компаньона - [User-Agent JS Fixer](https://addons.mozilla.org/ru/firefox/addon/user-agent-js-fixer/) (после этого whoer.net уже не ругается, что юзерагенты отличаются).

Random Agent Spoofer имеет две версии. Версия с AMO урезана по возможностям из-за тамошних правил (в описании аддона приведен список различий). На гитхабе полная версия, которая умеет блокировать <сanvas>, очищать window.name (тот же ip-check.info очень ругается на неочищенный заголовок), подменять часовой пояс/разрешение экрана, etc.

**Comment by The-OP** [comment]
Да, addendum давно пора переписать. Надо будет заняться. Почти со всеми уточнениями согласен.

>опция network.http.referer.XOriginPolicy
Опция-то есть, но еще есть сайты, у которых статика размещена на совершенно другом домене и не отдается без реферера с главного. Поэтому RefControl лучше.

>Privacy Badger и т.п.
Это я вообще думаю выкинуть за относительную бесполезность.

**Comment by The-OP** [comment]
Причесал немного. UAControl и User-Agent JS Fixer не стал добавлять из-за этого: https://addons.mozilla.org/ru/firefox/addon/user-agent-js-fixer/reviews/666020/

**Comment by firefoxForUser** [comment]
User-Agent JS Fixer полезен в плане обмана сайтов, которые например суют рекламу в онлайн видео и чтобы Adblock Plus не блокировал засовывают это в Flash plugin. Они по user agent определяют что за браузер зашел и десктоп пользователей заставляют ставить плагин, а тем кто с смартфонов показывают html5 (чтобы аудиторию расширить). Понятно, что они могут и те атрибуты учитывать, но это уже сложнее чем просто стандартный код использовать.
И да, это плохие сайты и на них не нужно ходить, но бывает, что на них есть уникальная инфа, которой больше нет нигде или есть, но искать другой сайт долго.
Видео я привел только, как пример. Может быть много варинатов. Да и код там достаточно прост в крайнем случае кому понадобится может его дополнить сам или изменить (отключив в настройках проверку подписи дополнений конечно).
