### ISSUE TITLE
баг с падением Firefox 38 ESR

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#34]
У многих наблюдается этот баг.
Решение https://support.mozilla.org/en-US/questions/1033429

**Comment by firefoxForUser** [comment]
И ещё на форумах описаны случаи когда на некоторых системах Firefox запускался с почти полностью белым окном из-за аппаратного ускорения. Так что его лучше совсем выключить.

**Comment by The-OP** [comment]
Отключение ускорения и OMTC есть в FAQ. Или дописать что-то надо?

**Comment by firefoxForUser** [comment]
В FAQ написано, что "если проблемы с интерфейсом". Тогда как у многих (включая меня) сразу после перехода версии 38 на ветку esr при малейшей нагрузке Firefox просто падает. С интерфейсом при этом всё в порядке.

Я уже через форму в Mozilla репортов 40 отправлял, даже email свой оставлял. Прошло 3 минирных релиза - никаких изменений. Версия ESR которая по сути должна быть стабильной хотя и ориентирована на админов компаний - пдает каждую минуту. А Mozilla не может не видеть репортов багов и их количества, значит просто игнорирует.

Причем на esr ветке основан TorBrowser. Он кстати падал только первые несколько версий, потом перестал в отличии от Firefox 38.

Подчеркиваю. Поиск по сети выдаёт такие же проблемы не только у меня.

**Comment by The-OP** [comment]
Так лучше: 022fb72?

**Comment by firefoxForUser** [comment]
да
