### ISSUE TITLE
выдилить особо опасные функции

### ISSUE THREAD

**Issue by firefoxForUser** [The-OP/Fox#36]
Предлагаю выделить особо опасные функции Firefox, которые в отличии от капель статистики, которые только косвенно могут выдать действия пользователя, могут сказать совершено точно что пользователь делал и где он был.

То есть или выделить их в отдельный файл, а может и в FAQ, или как-то отметить в ваших подборках настроек.

Зачем это надо. Многим людям всё равно, что там из статистики отправляется. В том числе программистам, представляющим что это такое. Но вот когда им говоришь, что отправляются хэши файлов, данные сенсоров, а запросы идут в обход прокси даже они начинают возмущаться. :)
Вот для этой группы, которая хочет отключить "опасное, да ещё и ненужное никому для работы" был бы полезен такой FAQ.

Вот какие лично я вижу сейчас опасные функции:
1. Какой прокси не ставь DNS всё расскажет.
user_pref("network.proxy.socks_remote_dns", true);
2. В сервисе проверки файлов абсолютно точно будут знать что именно качал пользователь.
user_pref("browser.safebrowsing.downloads.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
3. Слишком много уязвимостей при том, что его заменит любой свободный просмотрщик.
user_pref("pdfjs.disabled", true);
user_pref("pdfjs.enableWebGL", false);
4. Можно с большой точностью вычислить пользователя. Игры (по крайней мере сегодня) не для web. (и возможно что-то ещё из webgl)
user_pref("webgl.disable-debug-renderer-info", true);
user_pref("webgl.disable-extensions", true);
user_pref("webgl.min_capability_mode", true);
5. Уровень заряда, коды клавиш практически точный профиль пользователя при том, что сайту его знать не надо. Разные API.
user_pref("dom.battery.enabled", false);
user_pref("device.sensors.enabled", false);
user_pref("dom.gamepad.enabled", false);
user_pref("dom.gamepad.non_standard_events.enabled", false);

**Comment by The-OP** [comment]
Не знаю, что такое *особо опасные* функции. Тут вроде все направлено на то, чтобы браузер меньше стучал. Вот, например. информация о размерах окна - это опасная функция или нет? А ее в конфиге не отключишь, только при помощи Random Agent Spoofer (ну или UserJS).

**Comment by Kakadu** [comment]
А что рекомендуется вместо pdfjs?

**Comment by dartraiden** [comment]
Любой десктопный PDF-вьювер, кроме Adobe Reader.

**Comment by firefoxForUser** [comment]
Любой СВОБОДНЫЙ. :)
Например Sumatra PDF, который ещё и djvu показывает и ядро у него портировано с linux утилиты. И что забавно в wine он работает быстрее всех других вменяемых программ родных для linux. :)

**Comment by dartraiden** [comment]
Я когда-то давно перепробовал все свободные, что нашёл (для Windows): у кого-то нет запоминания последней открытой страницы, у кого-то тормозная прорисовка. Так что, пришлось разменять свободу на удобство и остановиться на X-Change Viewer, который вдобавок еще и OCR умеет (иногда встречаются PDF без текстового слова, свёрстанные из изображений)

**Comment by The-OP** [comment]
@firefoxForUser
Если честно, я так и не понял, что ты хочешь. Вышеописанные опасные функции есть в prefs_1/2, которые в общем случае можно накатывать себе целиком, не глядя в каждую строчку и не опасаясь, что что-то нужное для работы сломается. Зачем их куда-то дублировать и по какому принципу?

**Comment by firefoxForUser** [comment]
Просто мне показалось, что для многих людей было бы удобнее выписать настройки, которые позволяют определить что и как делал пользователь без анализа данных и с вероятностью близкой к 1-це. Это чтобы не пришлось выбирать их из списка.

Самая страшная из них - отсылка хэш сумм. Лично я до сих пор немного в шоке от такого, не ожидал от Mozilla. Это нельзя оправдать никак.

**Comment by The-OP** [comment]
>для многих сайтов, которые по сути веб приложения, придется использовать почти чистые профили

Так я про то и говорю - с prefs_1/2 и не должно ничего нужного ломаться. Если где-то что-то ломается - пиши, даунгрейдну до третьего файла. Пока заметил кое-где поломки только от отключения Indexed DB (но никто больше не жаловался, поэтому оставил пока в prefs_2). Причем она там даже не используется - просто ее поддержку добавили в какой-то популярный фреймворк, но не удосужились обработать ситуацию с отключенной IDB.

**Comment by PlayerName** [comment]
В prefs_1.js есть настройка отключение 3DES
user_pref("security.ssl3.rsa_des_ede3_sha", **false**);
Если выключит то ломается страница логина скайпа https://login.skype.com/login
Сделайте пометку что при запрете 3DES, могут некорректно отображаться некоторые сайты
