### ISSUE TITLE
webrtc лик

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#37]
С появлением параметра media.peerconnection.ice.relay_only (true) в 42 версии можно не выключать весь вебртц, а только предотвратить утечку локального и публичного айпи адреса.

**Comment by The-OP** [comment]
Пруф?

**Comment by fenque** [comment]
![2015-09-22 21 48 11](https://cloud.githubusercontent.com/assets/5204968/10028185/ab86f012-6173-11e5-9fc8-a635343a6b4e.png)
С включенным параметром

**Comment by fenque** [comment]
https://wiki.mozilla.org/Media/WebRTC/Privacy

**Comment by fenque** [comment]
C  media.peerconnection.ice.default_address_only так же показал пустоту https://diafygi.github.io/webrtc-ips/

**Comment by The-OP** [comment]
Неплохо. Ты уже тестировал с этой настройкой некоторое время, и можно ее в prefs_1 добавить, не опасаясь что что-то отвалится? Hello нормально работает? И еще - в 41-то она работает или только в 42?

**Comment by fenque** [comment]
Появилась в 42, хелло исправно работает при этой настройке, думаю ничего отвалится не должно.

**Comment by The-OP** [comment]
Это хорошо. Добавлю, когда займусь 42 версией. Спасибо.

**Comment by The-OP** [comment]
64765fa - добавил, но default_address_only пока в закоментированном виде, ибо не работает с E10S. Надо будет следить за [тем багом](https://bugzilla.mozilla.org/show_bug.cgi?id=1194259) и раскомментировать, когда пофиксят.
