### ISSUE TITLE
Опции из 42

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#39]
http://cat-in-136.github.io/2015/09/diff-between-firefox-420-beta-1-default.html

Что заметил существенного:
* удалены browser.readinglist.enabled, browser.readinglist.sidebarEverOpened, readinglist.scheduler.enabled, readinglist.server
* добавлена browser.urlbar.userMadeSearchSuggestionsChoice. Если включить - работает точно так же, как и browser.search.suggest.enabled, только в адресной строке, вместо поисковой. [Подробности](http://techdows.com/2015/08/disable-firefox-search-suggestions-in-address-bar.html). По умолчанию выключена (пока)
* Отключена dom.mozPay.enabled. Какие-то платежи, для платных приложений в Firefox OS, наверное
* Парочка новых опций, связанных с Presentation API: dom.presentation.discoverable, dom.presentation.discovery.enabled
* Грядёт виртуальная реальность: dom.vr.oculus.enabled, dom.vr.oculus050.enabled. Не уверен, стоит ли это отключать
* Добавили loop.feedback.formURL. Если мы собираемся возвращать поддержку WebRTC и Hello, то можно не трогать
* Добавили privacy.trackingprotection.introURL. Поскольку. встроенная защита от отслеживания у нас отключается, нужно обнулить и этот урл

**Comment by The-OP** [comment]
Я еще в 42 вижу включенные Service Workers и пока не знаю, стоит ли отключать.

>browser.urlbar.userMadeSearchSuggestionsChoice

Третья опция для подсказок? Н-да. Было же уже browser.urlbar.suggest.searches

>удалены

Это все равно, в общем-то, до 45 ESR по крайней мере.

>возвращать поддержку WebRTC и Hello

Да не то чтобы возвращать, а просто в первую категорию добавить что-нибудь из #37 - там одна опция для разрешения соединений только через интерфейс с дефолтным маршрутом, а другая - для отключения P2P-соединений без сервера, как я понял. Вообще: (а) хорошо бы, если бы это все тестировал кто-то, использующий Hello, (б) тут уже плохо подходит формат один-конфиг-на-все-случаи жизни, лучше бы такие штуки настраивать каким-нибудь аддоном.

>cat-in-136

Кстати, я обнаружил, что этими диффами лучше не руководствоваться - там сравнивают один раз и ранние беты, а настойки могут появляться и в более поздних.

**Comment by firefoxForUser** [comment]
А ещё эти diff не сравнивают настройки из xul.dll которые не отображаются на странице about:config и действуют только при создании их пользователем вручную.
Можно искать по xul.dll как по текстовому файлу.

**Comment by The-OP** [comment]
64765fa
