### ISSUE TITLE
38 ESR 

### ISSUE THREAD

**Issue by corvo7** [The-OP/Fox#41]
Здравствуйте!Вся линейка 38 ESR  ну никак не хочет воспроизводить нормально видео MP4 ВК от ВКонтакте и на других сайтах без флэша.
31.7-31.8 ESR-работает все и везде без флэша.Все,что с YouTube встроено в ВК идет без проблем ,а MP4 долго запускается и виснет на перемотке-не грузится.Если ставлю в 38 media.fragmented-mp4.exposed в false,все работает,но браузер падает и потребляемая браузером память растет в геом.прогрессии-2 гб и больше.Перепробовал все,не могу решить проблему.А флэш ставить не хочу.Может Вы подскажете решение?

В тему ваших усилий http://wiki.kairaven.de/open/app/firefox

**Comment by The-OP** [comment]
Понятия не имею, если честно. Так или иначе, issues этого репозитория предназначены исключительно для обсуждения вносимых в находящуюся тут информацию изменений. За общими вопросами по использованию Firefox и прочей техподдержкой рекомендуется обращаться в тред в /s/ или на support.mozilla.org.
