### ISSUE TITLE
whoer.net и их продажность

### ISSUE THREAD

**Issue by nyanon** [The-OP/Fox#45]
У вас есть ссылка на него тут
https://github.com/The-OP/Fox/blob/master/addendum.md

Смотрите что за бред они пишут https://whoer.net/blog/article/why-tor-is-worse-than-vpn/

**Comment by The-OP** [comment]
Да, маркетинговая статья. Но она не делает хуже их анализ отпечатка, ради которого ссылка и поставлена.
