### ISSUE TITLE
Дополнение ZenMate и потенциальное шпионство

### ISSUE THREAD

**Issue by nyanon** [The-OP/Fox#46]
ZenMate - это популярное дополнение-анонимайзер с быстрыми прокси, которое ещё и шифрует трафик (так что можно через публичный wi-fi выходить). Это очень популярное дополнение, которое даже в избранное для firefox входит.

Для Firefox https://addons.mozilla.org/ru/firefox/addon/zenmate-security-privacy-vpn/
Для Chrome/Chromium https://chrome.google.com/webstore/detail/zenmate-security-privacy/fdcgdnkidjaadafnichfpabhfomcebme
Для Opera https://addons.opera.com/ru/extensions/details/zenmate-for-operatm/?display=en

Заметьте одну забавную особенность. На странице https://whoer.net/ru#extended можно заметить, что при первом входе на сайт дополнение всегда использует один и тот же DNS сервер из США, которые не совпадает с ip. А при повторных входах ip DNS == ip прокси.
(при этом если промежутки между входами короткие, то обращение к DNS в США не происходит)

И что же имеет хозяин прокси зная ваши dns при условии, что он и ip ваше знает?
А имеет он полную карту подключений "ip + сайт_который_посещался".

Если в дополнении можно найти кусок кода, который является счетчиком первого подключения (чтобы только первому dns перенаправлять в США), то можно написать abuse в Mozilla на сайте дополнения. Можно даже просто изложить свои подозрения, пусть проверят код.
У кого с английским хорошо прошу это сделать.

**Comment by The-OP** [comment]
DNS Leak что ли в ZenMate? Репортить бесполезно - ревьюеры AMO не следят за тем, чтобы дополнение было без багов, только чтобы не было вредоносных функций.
