### ISSUE TITLE
В prefs_1.js одна настройка ломает отображение сайтов

### ISSUE THREAD

**Issue by PlayerName** [The-OP/Fox#48]
В prefs_**1**.js есть настройка отключения 3DES
user_pref("security.ssl3.rsa_des_ede3_sha", **false**);
Если выключить то ломается страница логина скайпа https://login.skype.com/login
Сделайте пометку что при запрете 3DES, некорректно отображаются некоторые сайты

**Comment by The-OP** [comment]
bb8ef82
