### ISSUE TITLE
Культ карго

### ISSUE THREAD

**Issue by KOLANICH** [The-OP/Fox#5]
В третьем отключено всё подряд. Я не понимаю, зачем отключать всё подряд. Это очевидно снижает поверхность атаки, но необходимо учитывать, что это сильно увеличивает fingerprintability и сильно бьёт по функциональности. В конце концов можно доотключаться до того, что выкинуть огнелиса нахер и использовать lynx, а лучше putty.

**Comment by The-OP** [comment]
Очевидно, что третий - просто помойка для того, что не подходит в первые два, и не предназначен для использования целиком.

**Comment by KOLANICH** [comment]
>просто помойка
а не %yй их него делать помойку.

**Comment by The-OP** [comment]
Возможно, стоит сделать чертвертый и перенести часть туда, оставив в третьем отключение загружаемых шрифтов, слабых шифров, включение pinning и т.п. В любом случае сейчас третий не рекомендуется всем подряд - слишком там много мешающего повседневному серфингу.

**Comment by KOLANICH** [comment]
>Возможно, стоит сделать четвертый

И удалить его. Помойка не нужна. About:config интуитивно понятен в части "вырубить ненужную функцию/врубить экспериментальную". Хотя в последнее время от этого стали отказываться: кто бы мог подумать, что firefox hello - это loop. Кому не понятен, для того есть дополнение config descriptions. Впрочем большинство настроек недокументированы.

**Comment by The-OP** [comment]
Я понял твою точку зрения. Я с ней не согласен.
Issue пусть пока повисит в качестве напоминания разбить третий файл на два.

**Comment by dartraiden** [comment]
Есть предложение добавить в третий опцию plugin.scan.plid.all = false
Оно отключает обработку браузером вообще всех плагинов. Идеально для тех, кто не пользуется флешем и явой.
Может, даже и не в третий...

**Comment by KOLANICH** [comment]
>browser.eme.ui.enabled = false (полностью убирает из гуя опцию, включающую и выключающую поддержку DRM-контент, предварительно, конечно, лучше этот DRM отключить с помощью media.eme.enabled)

Вообще не понимаю, зачем такое нужно

>Есть предложение добавить в третий опцию plugin.scan.plid.all = false
Оно отключает обработку браузером вообще всех плагинов. Идеально для тех, кто не пользуется флешем и явой.

А также OpenH264. Хотя погуглил, high profile ещё не реализовали, так что пофиг.

**Comment by The-OP** [comment]
>plugin.scan.plid.all = false

Это только на Винде работает вроде:
http://kb.mozillazine.org/Plugin_scanning
http://kb.mozillazine.org/Flash#Not_detected_due_to_disabled_plugin_scan_for_PLIDs_-_Windows

>services.sync.enabled = false

От ее отключения вообще есть какой-то эффект, если нет Sync-аккаунта? Попробовал - ни вкладка Sync из Preferences ни исчезает, ни Create Account не отваливается.

>media.getusermedia.screensharing.allowed_domains
>network.notify.changed

Уже есть в prefs_2.

>loop.debug.twoWayMediaTelemetry = false

Добавил.

>dom.caches.enabled

Вот это тестирвать надо. Мне кажется, от этого может сам браузер начать плющить, как от отключения dom.indexedDB.enabled в свое время (Fx35), хотя раньше отключалось без проблем.

https://blog.wanderview.com/blog/2015/03/24/service-workers-in-firefox-nightly/

**Comment by The-OP** [comment]
9377439e18
