### ISSUE TITLE
ERROR: Required file webapprt/omni.ja:defaults/preferences/prefs.js was not found in firefox_48.0a1-central-2016-04-03-03-02-43_en-US_linux-x86_64.

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#50]
```
./fx-diff-prefs.js firefox_45.0.1_linux-x86_64_en-US firefox_48.0a1-central-2016-04-03-03-02-43_en-US_linux-x86_64
ERROR: Required file webapprt/omni.ja:defaults/preferences/prefs.js was not found in firefox_48.0a1-central-2016-04-03-03-02-43_en-US_linux-x86_64.

```

**Comment by The-OP** [comment]
Да, на Nightly не тестировал. Они переместили эти настройки в другой файл?
Какие будут предложения? Подставить еще один вопросик в листинг? Мне не хотелось бы лепить костыли с зависимостями существования того или иного файла для каждой версии Firefox.

**Comment by soredake** [comment]
Файлик вот сюда переехал firefox_48.0a1-central-2016-04-03-03-02-43_en-US_linux-x86_64/firefox/browser/omni.ja/defaults/preferences

**Comment by The-OP** [comment]
А мне кажется, его вообще выпилили. Так или иначе: c829e25

**Comment by soredake** [comment]
Не выпилили, я же нашел его по тому пути.

**Comment by The-OP** [comment]
>/browser/omni.ja/defaults/preferences

Скачал 48 - не вижу его там. Что я делаю не так?

**Comment by soredake** [comment]
` wget https://ftp.mozilla.org/pub/firefox/nightly/2016/04/2016-04-03-03-02-43-mozilla-central/firefox-48.0a1.en-US.linux-x86_64.tar.bz2 && tar xvjf firefox-48.0a1.en-US.linux-x86_64.tar.bz2 && unzip -o -d firefox/browser/omni.jar firefox/browser/omni.ja; echo "Вот же он:" && ls -l firefox/browser/omni.jar/defaults/preferences/devtools* `

**Comment by soredake** [comment]
Спутал его с другим файлом, так что да, выпилили, а что в нем было, собственно?

**Comment by The-OP** [comment]
Ничего важного - куски от Firefox OS. Например:

https://developer.mozilla.org/en-US/docs/Archive/Marketplace/API/Navigator_%28Marketplace%29/mozPay
>Marketplace feature removal
>The functionality described on this page no longer works  Firefox Marketplace has discontinued support for Android, Desktop, Tablets, and payments (and other related functionality). For more information, read the Future of Marketplace FAQ.

**Comment by soredake** [comment]
Значит можно закрывать.
