### ISSUE TITLE
Куда уехали datareporting.healthreport.*?

### ISSUE THREAD

**Issue by dartraiden** [The-OP/Fox#53]
Собственно, [сабж](https://cat-in-136.github.io/2016/04/diff-between-firefox-460-default.html). Оно теперь неотключаемо в принципе, или просто их существование по дефолту выпилили?

**Comment by The-OP** [comment]
[Объединяют с телеметрией](https://wiki.mozilla.org/Unified_Telemetry) помаленьку, видимо. Основное пока никуда не делось:
`datareporting.policy.dataSubmissionEnabled`
`datareporting.healthreport.uploadEnabled`
