### ISSUE TITLE
media.peerconnection.ice.default_address_only

### ISSUE THREAD

**Issue by ghost** [The-OP/Fox#54]
Исправили, расскоменть.
https://bugzilla.mozilla.org/show_bug.cgi?id=1194259
https://bugzilla.mozilla.org/show_bug.cgi?id=1189041

**Comment by gineadai** [comment]
Объясни ещё почему `privacy.trackingprotection.introCount` закоменчено.

**Comment by The-OP** [comment]
>Исправили

Исправили в 46, а в ESR осталось. Я подумаю, но скорее всего эта штука с нами до следующего ESR. Не хочется опять делать разветвление. Опять же надо решить, что оставлять - это или `media.peerconnection.ice.relay_only`.

>почему privacy.trackingprotection.introCount закоменчено.

Потому что пока что менять его не имеет смысла, судя по коду. И, пожалуйста, не надо несколько разных вопросов писать в один issue.

**Comment by gineadai** [comment]
> но скорее всего эта штука с нами до следующего ESR
До 52? Окей.
>Опять же надо решить, что оставлять - это или media.peerconnection.ice.relay_only.
В user.js от pyllukko и от ghacks есть только `default_address_only`
> И, пожалуйста, не надо несколько разных вопросов писать в один issue.
Извини, не буду.

**Comment by dartraiden** [comment]
Полагаю, что теперь действительно можно выкинуть `media.peerconnection.ice.relay_only` в пользу `media.peerconnection.ice.default_address_only`, поскольку старый ESR уже всё.

**Comment by The-OP** [comment]
bb961f0
