### ISSUE TITLE
about:addons в Firefox 47+ не работает если значение browser.history.maxStateObjectSize ниже 160

### ISSUE THREAD

**Issue by ghost** [The-OP/Fox#56]
Если ниже 160, то нельзя переходить по категориям, в настройках наверное так же. 
Возможно связано с тем что данные настройки были удалены:
```
browser.history.allowPopState
browser.history.allowPushState
browser.history.allowReplaceState
```

**Comment by AlxMxlA** [comment]
Почему:
- закоментированы user_pref("privacy.trackingprotection.introCount", 1), user_pref("browser.fixup.hide_user_pass", false), user_pref("media.peerconnection.ice.default_address_only", true);
- именно 20 лет в user_pref("geo.wifi.timeToWaitBeforeSending", 630720000);
- user_pref("dom.workers.enabled=false", false), user_pref("dom.workers.websocket.enabled=false", false), user_pref("app.update.url.override", ""), user_pref("javascript.use_us_english_locale", true) отсутсвуют в user,js;
- у network.http.sendSecureXSiteReferrer изначально стояло true;
Что даст использование user_pref("webgl.enable-debug-renderer-info", false) на версиях до 42?
Указанные параметры маскировки как-то влияют на работоспособность браузера и правильность отображения страниц?

**Comment by The-OP** [comment]
Спасибо за информацию. 4ce3d1c

**Comment by The-OP** [comment]
@AlxMxlA Это все не имеет отношения к этому issue, лучше завести новый (или несколько).

**Comment by stepshal** [comment]
`browser.history.maxStateObjectSize` в ноль теперь уже какое-то время ломает кнопки 'More" и "Preferences" в about;addons. Тупо не нажимаются.
