### ISSUE TITLE
network.http.sendSecureXSiteReferrer

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#59]
У настройки network.http.sendSecureXSiteReferrer изначально стоит true.
Разве, в случае обеспечения запрета отсылки реферов, не должно стоять false?

**Comment by The-OP** [comment]
Не имеет смысла со включенным spoofSource. Там же приложена ссылка на исходник.

**Comment by AlxMxlA** [comment]
> Не имеет смысла со включенным spoofSource.

Будет мешать как-то или конфликтовать?

**Comment by stepshal** [comment]
Так в Торе или в JonDonym настройки рефёрера же не спуфят?

**Comment by The-OP** [comment]
@AlxMxlA Не будет. Просто не имеет смысла.

@stepshal И?
