### ISSUE TITLE
Интересное дополнение

### ISSUE THREAD

**Issue by fenque** [The-OP/Fox#6]
http://fxprivacy.8vs.ru/

**Comment by The-OP** [comment]
Интересное, но автор вроде забил из-за долгого ревью-процесса, не?

https://addons.mozilla.org/firefox/addon/http-useragent-cleaner/

**Comment by dartraiden** [comment]
На AMO забил, у себя на сайте пилит. Впрочем, в связи с грядущим принудительным подписыванием куда он денется...

**Comment by The-OP** [comment]
a035f4d3b1
