### ISSUE TITLE
Разъяснения по webgl.enable-debug-renderer-info

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#60]
Что даст использование user_pref("webgl.enable-debug-renderer-info", false) на версиях до 42? Указанные параметры маскировки как-то влияют на работоспособность браузера и правильность отображения страниц?

**Comment by The-OP** [comment]
Ничего, учитывая, что в 38 ее нет.
Запрет этого конкретного расширения? Не должно.
