### ISSUE TITLE
Safebrowsing

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#62]
Safebrowsing как-то влияет/может влиять на стандартную Защиту от отслеживания (которая Disconnect.me)?

**Comment by The-OP** [comment]
Я не понимаю вопроса. Может имелось в виду "отключение Safebrowsing как-то влияет [...]"?

**Comment by AlxMxlA** [comment]
> Может имелось в виду "отключение Safebrowsing как-то влияет

Именно.

**Comment by The-OP** [comment]
Вообще, я не проверял отключение одного без другого. 

Кроме очевидных `privacy.trackingprotection.*` и `browser.trackingprotection.*`, а также `urlclassifier.trackingTable`, `urlclassifier.trackingWhitelistTable`, есть еще `browser.safebrowsing.provider.mozilla.*` - там видны какие-то track-таблицы. Можно поэкспериментировать, если хочется оставить Tracking Protection. В `urlclassifier.disallow_completions` еще можно оставить moz-списки, убрав goog.
