### ISSUE TITLE
Генеральная уборка 2

### ISSUE THREAD

**Issue by stepshal** [The-OP/Fox#63]
```
browser.readinglist.sidebarEverOpened
browser.safebrowsing.provider.google.appRepURL
browser.safebrowsing.reportErrorURL
browser.safebrowsing.reportGenericURL
browser.safebrowsing.reportMalwareErrorURL
browser.safebrowsing.reportMalwareURL
browser.safebrowsing.reportURL
browser.trackingprotection.gethashURL
browser.trackingprotection.updateURL
devtools.appmanager.enabled
loop.contacts.gravatars.promo
loop.contacts.gravatars.show
loop.contextInConversations.enabled
loop.debug.twoWayMediaTelemetry
loop.feedback.baseUrl
loop.screenshare.enabled
loop.seenToS
loop.showPartnerLogo
media.audio_data.enabled
media.format-reader.mp4
media.fragmented-mp4.enabled
media.fragmented-mp4.exposed
media.fragmented-mp4.ffmpeg.enabled
media.fragmented-mp4.gmp.enabled
media.mediasource.format-reader
media.mediasource.format-reader.mp4
media.mediasource.format-reader.webm
network.auth.allow-subresource-auth
network.http.spdy.enabled.http2draft
network.http.use-cache
pfs.datasource.url
plugins.enumerable_names
readinglist.scheduler.enabled
readinglist.server
security.tls.insecure_fallback_hosts.use_static_list
webgl.disable-debug-renderer-info
```

**Comment by The-OP** [comment]
Спасибо, погляжу. MXR только вот что-то уже не первый день лежит.

**Comment by stepshal** [comment]
> MXR 
Это что?

**Comment by dezhavu** [comment]
ты небось reset'ом проверял в about:config ?
на самом деле больше настроек, которых вроде нет, но на mxr проверять, имхо можно упустить некоторые, того же privacy.resistFingerprinting там нет, как и многих других
разве что у cat-in-136.github.io взять разницы и скриптом пройтись, который еще написать надо :)

**Comment by stepshal** [comment]
> ты небось reset'ом проверял в about:config ?
Скриптами ЗеОП сравнил и потом на чистом профиле проверил.
> privacy.resistFingerprinting 
Это вообще работает? Где сведенья?

**Comment by The-OP** [comment]
>Это что?

https://mxr.mozilla.org/

**Comment by stepshal** [comment]
@The-OP Поднялось,  Теперь это https://dxr.mozilla.org/

**Comment by stepshal** [comment]
Проверю все настройки там, галочки проставлю если совпадает.

**Comment by stepshal** [comment]
@The-OP оставил в списке то чего нет в DXR 45 версии без остатка.

**Comment by The-OP** [comment]
@stepshal Это хорошо конечно, но можно было и не делать. Удаления я все равно сам тщательно проверяю.

**Comment by The-OP** [comment]
dd526c4
