### ISSUE TITLE
Разъясни пару вещей по рекомендуемым аддонам (RefConfrol, RAS, uMatrix)

### ISSUE THREAD

**Issue by wallofbytes** [The-OP/Fox#64]
Здравствуй, бро. По тебе очень скучают в тредике, без тебя он совсем скурвился. Накопилось несколько вопросов по твоим гайдам, на которые там никто ответить не может, поэтому спрошу у тебя лично, если тебя не затруднит дать какие-нибудь комментарии.

1) Спуфинг реферера
Первоначально поставил твои префсы из prefs_2.js:
```
user_pref("network.http.referer.spoofSource", true);
user_pref("network.http.referer.trimmingPolicy", 2);
user_pref("network.http.sendRefererHeader", 2);
user_pref("network.http.referer.XOriginPolicy", 0);
user_pref("network.http.sendSecureXSiteReferrer", true);
```
Некоторые сайты перестали работать, поэтому надо это дело чем-то заменить. Чем-то с белым списком. При этом вот эти настройки перезапишутся сами или их надо откатить до дефолтных, чтобы не было проблем? И главное - зачем ты советуешь RefControl, если матрица содержит весь его функционал. И RAS содержит. Подробнее чуть ниже.

2) Агент спуфер. Когда-то это было замечательное приложение, пока не разрослось. Теперь там куча галочек, некоторые из которых перекрывают твои префы, другие, боюсь, могут твои префы поломать. Два скрина: на первом дефолтные настройки, на втором накат поверх твоих префов. 

![1](https://cloud.githubusercontent.com/assets/18580942/16285961/ea549ed4-38e1-11e6-811c-36c46ac7819d.png)
![2](https://cloud.githubusercontent.com/assets/18580942/16285960/ea53ad76-38e1-11e6-9d24-dab926f60e76.png)

Какие из этих галочек стоит ставить и есть ли смысл их вообще трогать либо же оставить все по дефолту? Если сам им пользуешься - подскажи свой конфиг, если нет, подскажи, как примерно с ним себя вести, а если оставлять все по дефолту - не лучше ли его заменить, опять же, мюматриксом? Особенно интересны вот эти галочки с реферером на первой панельке, какие-то хитрые настройки, у других такого нет.

3) Матрица. Это круто, что она содержит в себе функционал RAS и RefControl одновременно (пусть и не в таком красивом виде), белый список, да еще и хочет быть заменой контролеру кук, НО у меня другой вопрос: зачем нужны подписки и подписочный контроль матрицы при наличии uBlock? Ведь там одинаковые списки, но у мюблока их больше. Они имеют одинаковое название и одинаковое либо сильном пересекающееся содержание. Или эти аддоны блокируют по этим спискам разные вещи? Не является ли это лишней нагрузкой? Пикрелейтед

![3](https://cloud.githubusercontent.com/assets/18580942/16285962/ea54cdfa-38e1-11e6-90af-4607df9da147.png)
![4](https://cloud.githubusercontent.com/assets/18580942/16285959/ea518c26-38e1-11e6-8086-63949125d730.png)

Кстати, будет бесконечно круто, если ты немножко расскажешь о том, какие у тебя самого стоят подписки и почему, какие ставить, а какие лучше не надо. Все-таки, память не бесконечная, листы эти огромные, наверное, чекать их не сильно быстро получается, особенно, если и родной hosts заполнен тоннами записей от всяких дисконнектов.

**Comment by The-OP** [comment]
>Некоторые сайты перестали работать

Какие?

>При этом вот эти настройки перезапишутся сами или их надо откатить до дефолтных, чтобы не было проблем?

Надо.

>зачем ты советуешь RefControl, если матрица содержит весь его функционал

Не весь, она может только спуфить. Кроме того, пускай будет выбор и альтернативы. 

>Какие из этих галочек стоит ставить

Standard options можно не трогать - это все обычные префы, которые есть и здесь. Польза там от раздела script injection, ну и может headers, если не английская локаль в браузере.

>Особенно интересны вот эти галочки с реферером

Эти галочки просто меняют те же самые префы, которые в prefs_2. В отличие от RefControl и uMatrix, которые работают независимо.

>зачем нужны подписки и подписочный контроль матрицы

С подписками в матрице сразу становятся явно заблокированы многие мусорные домены вроде doubleclick. Это наглядно видно в интерфейсе - и можно сразу их отсеивать, не пытаясь разрешать при настройке.

>листы эти огромные, наверное, чекать их не сильно быстро получается

uBlock умеет определять дублирующие друг друга правила из разных подписок.

**Comment by wallofbytes** [comment]
> Какие?

Авито, Саппорт Тинькофф-банка, ВОЗМОЖНО повторный поиск на яндекс-картинках. Но мб это с чем-то другим связано.

> Не весь, она может только спуфить. Кроме того, пускай будет выбор и альтернативы. 

А есть принципиальное различие между спуфингом и блокировкой? Ну окей, просто это немножко путаницу создает, когда куча аддонов с дублирующим функционалом.

> Польза там от 

А что скажешь насчет отключения вебгл, лимитед детектабл фонтс, css-visited, гибкие настройки, что прятать в dom. По-моему, не все это у тебя есть.

>С подписками в матрице сразу становятся явно заблокированы многие мусорные домены
Да, я понимаю, но они же блокируются и в мюблоке, я вот к этому.

>uBlock умеет определять дублирующие друг друга правила из разных подписок.

А с матрицей-то он как взаимодействует? Тоже определяет? Или я зря парюсь и даже дублирование списков в матрице и мюблоке сильно на быстродействии не скажется? Это я про:

>Все-таки, память не бесконечная, листы эти огромные, наверное, чекать их не сильно быстро получается, особенно, если и родной hosts заполнен тоннами записей от всяких дисконнектов.

Да, будет круто, если выложишь свои подписки к uBlock с какими-нибудь комментариями, мол, "это хуйня, только мороки добавит со всякими ебэями, а вот это годнота, рикаминдую"

Ослоу, еще пара вопросиков с твоего позволения: 

1. хотя это проблема шинды, возможно, а не фаерфокса. Лиса, вкладка с пикчей. Копировать изображение (с прозрачностью), вставить (в фотошоп, к примеру) - хуяк, черный фон. Бля, ну охуеть теперь. Это шинда не может в буфере обмена держать прозрачность? Как быть? Сохранять и открывать каждый раз заебывает. Можно копировать ссылку на изображение, а не само изображение, но это все равно надо новый файл открывать, он скопипастится во временную папку в c:/windows/... Хуйня, неудобно. 
2. Вы решили проблему с ебанутым колесиком загрузки (ака "часики") и ожиданием на белом фоне при загрузке страницы в e10s? Очень уж бесит, обычный фаерфокс в однопроцессном режиме держит показ старой страницы, пока не загрузится новая, без всяких раздражающих анимаций и не так скучно, как с белым фоном.

**Comment by The-OP** [comment]
>Авито

Да, это документировано. А вот остальное неплохо бы точно проверить и тоже документировать, если виноват именно реферер.

>А есть принципиальное различие между спуфингом и блокировкой?

От спуфинга меньше сайтов ломается.

>По-моему, не все это у тебя есть.

Проверил - по-моему все. Если тебе кажется, что не все, давай ты сам проверишь и выскажешь конкретные претензии.

>А с матрицей-то он как взаимодействует?

Запросы, которые были заблокированы одним аддоном, до другого просто не дойдут.

>Все-таки, память не бесконечная

Не вижу целесообразности в экономии на спичках.

>хотя это проблема шинды, возможно, а не фаерфокса

С багами - в багзиллу (или техподдержку MS), а не сюда. Исключение - если известен воркэраунд, который можно добавить в FAQ или файлы настроек.

>колесиком загрузки (ака "часики")

Попробуй удалить несовместимые с E10S аддоны и отключить Interposition.

>Да, как вот это-то спуфить

Что?

**Comment by wallofbytes** [comment]
https://addons.mozilla.org/ru/firefox/addon/privacy-settings/
Лови, специально в ФФ-треде караулил анона, который вбросил скрин. Мб тебе понравится. Что-то вроде твоих prefs.js с гуем.

**Comment by The-OP** [comment]
Видел - смысла нет особого.
