### ISSUE TITLE
decentraleyes

### ISSUE THREAD

**Issue by KOLANICH** [The-OP/Fox#68]
Есть какой-то мутный (в смысле почти нет GUI для настроек, возможно забыли приделать, а возможно так и было задуманно) аддон, https://github.com/Synzvato/decentraleyes, кеширующий контент, который не должен часто меняться (скрипты и картины с cdn), и предотвращающий запросы на сервера за этим контентом.

**Comment by The-OP** [comment]
Так я же его добавил уже.

**Comment by KOLANICH** [comment]
Тогда ОК.
