### ISSUE TITLE
→

### ISSUE THREAD

**Issue by deterenkelt** [The-OP/Fox#7]
### К header.md

> поисковый движки

Есть такой сайт, как http://mycroftproject.com — это нечто вроде addons.mozilla.org, только для поисковых движков. Там есть тучи двжков для гугло/яндекс/опенстритмапс, поиска по всяким торрентопомойкам (рутряхер, пиратбей, няя), kage project и т. п. Вроде к этому сйту даже аддон есть.

> прокрутка колесом мыши

Я последний год пользуюсь 

    user_pref("mousewheel.acceleration.factor", 1);
    user_pref("mousewheel.default.delta_multiplier_y", 270);

По крайней мере, мне кажется, что это именно те настройки, которые дают подстройку под себя.

> Как сделать скриншот всей страницы

Зачем эти начемоданечерезкитайские `Shift+F2 как-там-блядь-эта-команда?..` Есть же Screenshoter. Один клик на иконке и снимок страницы/части страницы/выделенное (как настроишь) отправляется в буфер обмена/в файл на диск (опять же как настроишь). Альтернатива основному действию на кнопке всегда доступна в меню ПКМ.

> Stylish. Меняет внешний вид сайтов и самого Лиса согласно UserCSS.

Чтобы изменить CSS на конкретном сайте или в самой лисе, необязательно заисрать память ещё одним аддоном же. В профайле в папке chrome лежат `userContent.css` и `userChrome.css` — в них пользователь может задавать свои стили для сайтов и внешнего вида браузера соответственно. Синтаксис для `userContent.css` прост: по умолчанию стиль применяется глобально ко всем сайтам, а персонально для fullofads.com, например:
 
    @-moz-document domain("fullofads.com") {
        .ads .some_other_ads {display: none !important}
    }

> Yet Another Smooth Scrolling. Тонкая настройка прокрутки, включая плавность, скорость и ускорение.

Н-но ведь FF сам всё это может через about:config…

От себя бы ещё порекомендовал 
[Download status bar](https://addons.mozilla.org/en-US/firefox/addon/download-status-bar/) — все скачанные файлы теперь видны полосой статусной строкой, есть настройки, в т. ч. какие файлы там не отображать.
[Google search by image](https://addons.mozilla.org/ru/firefox/addon/google-search-by-image/) — при клике ПКМ на изображениях в контекстное меню добавляется элемент для поиска этого изображения через Google image search.
[Image search options](https://addons.mozilla.org/en-US/firefox/addon/image-search-options/) — то же самое для IQDB, SauceNAO и т. п.. — фактически с этими двумя аддонами у вас куклоскрипт везде (*в хорошем смысле*). 
[History janitor](https://addons.mozilla.org/en-US/firefox/addon/history-janitor/) — так как Firefox умеет либо хранить историю, пока не треснет, либо не хранить вообще, её хорошо бы периодически подчищать, чтоб жирнолис не грузил её почём зря. Количество дней, за которые помнить ссылки на посещённые сайты — единственная настройка этого аддона.
[Lazarus](https://addons.mozilla.org/en-us/firefox/addon/lazarus-form-recovery/) — когда простыня уже быа накатана в пост, а он не отправился, бывает очень обидно. Lazarus помнит текст каждой формы так что его можно восстановить даже после краша. Внимание: по-умолчанию Lazarus держит в профайле базу на 4 ёбаные недели и её бекап. Я бы рекомендовал запретить бекапы и сократить время хранения текст форм до трёх часов — если произошло ЧП, то либо за это время пост будет отправлен, либо в этом уже скорее всего нет смысла.

### К prefs_2.js

> `// Не дает страницам узнавать когда и какая их часть была скопирована в буфер обмена.`
> `user_pref("dom.event.clipboardevents.enabled", false);`

А ещё флеш и js контент не будет иметь возможности юзать буфер обмена и всякие идентификаторы (как на tenhou.net, например) придётся набирать вручную, а выделенный текст (ссылки на реплеи и т. п.) будет не скопировать оттуда, что неудобно.

### К prefs_3.js

Этот файл выглядит как инструкция для кого-то нехорошего, кто собирается лазить в интернет за одними непотребствами на заведомо опасные сайты. Мне недостижимо зачем эти настройки нужны, я просто отмечу, что

> `// SPDY может хранить идентификатор и держит экстремально долгое открытое соединение.`
> `user_pref("network.http.spdy.enabled", false);`
> `user_pref("network.http.spdy.enabled.v3", false);`
> `user_pref("network.http.spdy.enabled.v3-1", false);`

…это выстрел себе в ногу, потому что SPDY есть зачатки HTTP/2. И на них весьма вероятно натолкнуться в интернете

> As of November 2014, approximately 2.3% of all websites support SPDY.[53]

Особенно учитывая, что разрабатывается он Google и все гуглосервисы на нём работают.

> Some Google services (e.g. Google search, Gmail, and other SSL-enabled services) use SPDY when available.[54]

Браузеры в основном повыкидывали старые версии SPDY, Chrome — ниже 3.1, Firefox — ниже 3.0
— https://en.wikipedia.org/wiki/SPDY
Но и без SPDY ничего отвалиться не должно, так что это скорее выкидывание вишенки с торта, чем выстрел в ногу.

> `user_pref("browser.cache.disk.capacity", 0);`
> `user_pref("browser.cache.disk.enable", false);`
> `user_pref("browser.cache.disk.smart_size.enabled", false);`
> `user_pref("browser.cache.disk_cache_ssl", false);`

Разве просто выключить `browser.cache.disk.enable` не достаточно?

> `user_pref("browser.cache.memory.enable", false);`

Казалось бы, какое отношение анализ кеша имеет к тому, что хранится, пока компьютер подключён к розетке? Разве что майор Иванов начнёт дознавание на месте.

> user_pref("media.cache_size", 0);

Ещё один потенциальный выстрел себе в ногу — вебмки будут очень плохо проигрываться и циклиться.  Этому кешу вообще лучше задавать что-то от 50 MiB.

### Ещё от себя

> 2015
> IPv6

`user_pref("network.dns.disableIPv6", true);`

Для тех, кто не выключает компьютер месяцами — `dom.storage.default_quota = 51200`. Кукла не расчитана на такое длительное время и её кеш в этом storage упирается в пятимегабайтный предел, который там стоит по умолчанию.

Для тех, кто сидит на X11 — `browser.urlbar.clickSelectsAll = false`, — когда у тебя в буфере обмена ссылка, которую ты хочешь вставить в адресную строку, ты кликаешь по адресной строке, и… ссылка, которая там была, выделяется и сама попадает в буфер обмена, затирая нужную. Этот параметр предотвращает такое поведение.

Вообще, при достаточном количестве памяти (читай, на нормальном десктопе) дисковый кеш не нужен и будет только лишними тормозами для нешустрой лисы. Поэтому кеш в памяти — побольше, кеш на диске — долой. После этого внимание на `browser.sessionhistory.max_total_viewers` — описание тут где-то было, это количество «готовых» страниц, которые браузер держит в памяти в истории вкладки. Ну и uBlock.

**Comment by The-OP** [comment]
Я бы попросил впредь не запихивать все в один issue - очень сложно обсуждать такую простыню. Тут как минимум на три-четыре части можно разбить.

>нечто вроде addons.mozilla.org, только для поисковых движков

Чем это лучше Add to Search Bar?

>В профайле в папке chrome лежат userContent.css и userChrome.css

Это всем известно, но Stylish гораздо удобнее и работает без перезапуска браузера.

>Firefox умеет либо хранить историю, пока не треснет

Пока не достигнет places.history.expiration.transient_current_max_pages. Раньше как раз история по возрасту выкидывалась, теперь - по числу элементов, которое рассчитывается в зависимости от мощности машины.

>А ещё флеш и js контент не будет иметь возможности юзать буфер обмена

И это хорошо. Или в смысле в описание это добавить?

>это выстрел себе в ногу

Так можно про весь prefs_3 скзаать. Но будет дорабатываться. См. #5

>И на них весьма вероятно натолкнуться в интернете

Без фоллбэка?

>Разве просто выключить browser.cache.disk.enable не достаточно?

Принцип тот же, что и с остальными настройками (даже отключенными по дефолту в нынешнем stable) - лучше перебдеть.

>Казалось бы, какое отношение анализ кеша имеет к тому, что хранится, пока компьютер подключён к розетке?

В addendum же есть ссылки на сайты, анализирующие отпечаток. Кэш это https://en.wikipedia.org/wiki/HTTP_ETag

>вебмки будут очень плохо проигрываться и циклиться

Да вроде нормально проигрываются (у меня на Fx41). Кроме того, тех, кого интересует prefs_3, заинтересуют webm и наоборот.

>dom.storage.default_quota = 51200. Кукла не расчитана на такое длительное время и её кеш в этом storage упирается в пятимегабайтный предел

А что должно произойти, собственно? Я как раз не выключаю подолгу и использую Куклу - проблем не замечал.

>на нормальном десктопе) дисковый кеш не нужен и будет только лишними тормозами

На нормальном десктопе SSD есть. Memory-кэш, очевидно, пуст при перезапуске браузера.

**Comment by deterenkelt** [comment]
> Я бы попросил впредь не запихивать все в один issue - очень сложно обсуждать такую простыню. 

Ну извени, я как бы не был уверен, что ответ вообще последует.

> Чем это лучше Add to Search Bar?

Проглядел. Но вот щас поставил его, тыкнул в поле поиска аддонов на addons.mozilla.org добавил кейворд, все дела. Пробую найти этот самый аддон, а в ответ «Secure connection cannot be established…».

> но Stylish гораздо удобнее

Субъективно.

> теперь - по числу элементов, которое рассчитывается в зависимости от мощности машины.

То, что у меня ещё есть терабайты свободного места, не означает, что я хочу хранить историю со времён царя гороха. Тем более что я сижу в браузере круглые сутки.

> И это хорошо. Или в смысле в описание это добавить?

Это может быть неудобно. Да, я хотел бы, чтобы предупреждение об этом было в описании. Желательно как-то более кратко, навроде «если вы часто копируете что-то из флеша, оно перестанет работать».

> Без фоллбэка?

С фоллбеком, но зачем тогда ставить FF, `links -g` там →

>  Кэш это https://en.wikipedia.org/wiki/HTTP_ETag

А-а, понятно. 

> Да вроде нормально проигрываются (у меня на Fx41).

У меня были страшные лаги, когда размер вебмки не умещается в медиа кеш, она после итерации в лупе херит начало (хотя, если судить по полоске предзагруженного контента в HTML5 плеере, то херит вообще всё) и выкачивает его заново, а в это время `<video>` тормозит.

> Кроме того, тех, кого интересует prefs_3, заинтересуют webm и наоборот.

В смысле «не заинтересуют?». Но там же как раз все кодеки кроме тех, что для вебм, отключаются?

> `// Отключение поддержки кодеков, кроме WebM (он будет воспроизводиться при нажатии).`

Да и кто ж знает, кому взбредёт напихать в свой prefs.js (кстати, почему не user.js?) каждой твари по паре из этих конфигов?

> А что должно произойти, собственно?

https://github.com/SthephanShinkufag/Dollchan-Extension-Tools/issues/748

> На нормальном десктопе SSD есть.

А ещё 32 гигабайта памяти. Хотя мне и с восемью ничто не мешает жить без диского кеша. Даже если SSD есть, он может быть отведён под системный раздел (особенно, если это гибрид), в то время, как кеш пользователя может находиться за его пределами (ну, [если не мудрствовать лукаво](https://support.mozilla.org/ru/questions/955978)). Так, в GNU/Linux домашние папки находятся под /home, который, как правило, назначается на самый большой раздел, обычно отдельный от системного (система — отдельно, пользовательские данные — отдельно, можно грохать системный раздел, ставить систему заново или вообще другой GNU/Linux не боясь их потерять).

> Memory-кэш, очевидно, пуст при перезапуске браузера.

Когда браузер днями/неделями/месяцами не выключается, это не суть важно же.

**Comment by The-OP** [comment]
Кстати, еще по первому посту - я не очень понял, зачем отключать IPv6.

>Пробую найти этот самый аддон, а в ответ «Secure connection cannot be established…».

Проверил - работает. Проблема у тебя.

>Субъективно.

Комментировать боки одного мегафайла и перезапускать браузер удобнее?

>терабайты свободного места

Там не от места, а от процессора и памяти по-моему считается. Чтобы поиск в places.sqlite не был слишком тормозным.

>я хотел бы, чтобы предупреждение об этом было в описании

Добавил.

>У меня были страшные лаги, когда размер вебмки не умещается в медиа кеш

Тестировал как раз с media.cache_size 0.

>там же как раз все кодеки кроме тех, что для вебм

Да, там ошибка - webm тоже надо отключать по идее. Поправил.

>Да и кто ж знает, кому взбредёт напихать в свой prefs.js (кстати, почему не user.js?) каждой твари по паре из этих конфигов?

Предупреждение висит. Проблемы тех, кто не читает.

>dom.storage.default_quota = 51200

С этим понятно, но не знаю куда его приткнуть. Редкий юзкейс и 50 МБ - это как-то чересчур. Session storage у Firefox хранится в том же файле, что и сессия (вкладки и окна), а некотоые сайты очень любят туда гадить - например, Гугл-картинки чуть ли не мегабайт записывают (помнится, в треде кто-то жаловался что у него из-за этого сессии раздуваются). Поэтому рекомендовать такое значение я бы не стал.

>Хотя мне и с восемью ничто не мешает жить без диского кеша.

В том-то и дело, что дисковый придется отключить, т.к. иначе изменение объема memory-кэша мало что даст - Firefox будет писать на диск еще до его заполнения. Поэтому эта настройка была выкинута из prefs_2.

>Когда браузер днями/неделями/месяцами не выключается, это не суть важно же.

Опять же редкий юзкейс для того, кто точно знает, что он делает. А по умолчанию рекомендовать такое нехорошо. Разве что создать еще один файл с настойками для маньяков-экспериментаторов.

**Comment by The-OP** [comment]
Добавил увеличение мемори-кэша и sessio storage сюда: https://github.com/The-OP/Fox/blob/master/prefs_exp.js

**Comment by deterenkelt** [comment]
> Кстати, еще по первому посту - я не очень понял, зачем отключать IPv6.

Много ты юзаешь сервисов, работающих через IPv6? 

> Проверил - работает.

Сегодня и у меня работает. Странна.

> Комментировать блоки одного мегафайла
> мегафайла

Какого мегафайла, лол? Он же пустой почти бай дефолт.

> и перезапускать браузер удобнее?

Мысль держать работающим в памяти лишний аддон, который может ещё имеет свои мегабайты пер таб, мне более противна, чем перезастить бразуер. Я это делаю ради правки CSS не так часто. Последний раз вырезал кнопки на MAL два-три месяца назад.

> Тестировал как раз с media.cache_size 0.

Некоторые настройки в лисе требуют перезапуск.

> Предупреждение висит. Проблемы тех, кто не читает.

Открыл prefs_3.js, не увидел предупреждений. Или они там где-то в самом низу в комментариях к какой-то конкретной строке?

> Редкий юзкейс и 50 МБ - это как-то чересчур. 

Навряд ли FF отожрёт 50 МиБ сразу при старте — кеш же он постепенно заполняет.

> В том-то и дело, что дисковый придется отключить, т.к. иначе изменение объема memory-кэша мало что даст 

Естессно. Я ж с того и начал, что «дисковый кеш не нужен».

> Опять же редкий юзкейс для того, кто точно знает, что он делает.

Да ну, в общем-то и запустить один раз с утра тоже погоды не делает.

> Добавил увеличение мемори-кэша и session storage

Можно добавить ещё, что изменеие memory.* параметров требует рестарт, а объём памяти на элемент слизан с настроек дискового кеша, т. к. FF из коробки предлагает хранить в памяти только мелочь.

**Comment by deterenkelt** [comment]
> Редкий юзкейс и 50 МБ - это как-то чересчур. 

Ну, во-первых, 50 мегабайт — это не я рекомендую, а Степан, во-вторых, можно было в prefs_exp.js оставить ссылку на баг если кому-то 10 метров не хватит.

**Comment by The-OP** [comment]
>не увидел предупреждений

https://github.com/The-OP/Fox/blob/master/addendum.md#Настройки

>оставить ссылку на баг если кому-то 10 метров не хватит.

Добавил.
