### ISSUE TITLE
Способы установки неподписанных аддонов на >=48

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#70]
https://gist.github.com/anonymous/a661949550a26b9522f79095f8ae2d94
https://geektimes.ru/post/279132/#comment_9480372

**Comment by The-OP** [comment]
Ага, видел. Через конфиг лучше способ. Кстати, в дистрибутивах мейнтейнеры собирают с отключенной опцией обязательных проверок подписей.

**Comment by soredake** [comment]
> Кстати, в дистрибутивах мейнтейнеры собирают с отключенной опцией обязательных проверок подписей.
Не во всех, к сожалению.

**Comment by The-OP** [comment]
А где нет?

**Comment by The-OP** [comment]
f13cf37

**Comment by soredake** [comment]
@The-OP в Gentoo, там только своим патчем выпилить можно.

**Comment by The-OP** [comment]
>Gentoo

Довольно неожиданно.

Ну ладно, я закрываю, если других замечаний и предложений нет.
