### ISSUE TITLE
watch with mpv

### ISSUE THREAD

**Issue by soredake** [The-OP/Fox#71]
Но зачем? Есть же https://github.com/darktrojan/openwith с большим функционалом, позволяющий открывать не только mpv

**Comment by The-OP** [comment]
Да пусть будет. 

>openwith

Мне не нравятся поползновения автора этой штуки встроить зонд даже в такое простое расширение.

**Comment by nyanon** [comment]
FlashGot удобнее. Туда в меню можно добавить любой плеер, хоть SMPlayer, хоть VLC.
