### ISSUE TITLE
О нужности ScrapBook X

### ISSUE THREAD

**Issue by nyanon** [The-OP/Fox#72]
Я когда-то пользовался ScrapBook Plus. У меня накопилось за 1000 сохранённых страниц. Всё было разделено и разложено по каталогам. В результате очередного обновления Firefox дополнение ScrapBook Plus не успело обновиться и я получил геморрой. Потому что файлы при сохранении не аккуратно сохранены в профиле (по крайней мере были раньше) и я не смог их перекинуть. Да ещё ресурсы. Кроме того, если вы захотите залить файл в интернет или скинуть кому-то нужны будут дополнительные телодвижения.

Когда файлов ОЧЕНЬ много на слабых нетбуках начинает тормозить (спасибо Firefox конечно, дополнение не при чем, но имеем то что имеем). То есть если ваш комп сломается и вы временно пересядете за слабый домашний нетбук (перекинете профиль), то получите слайдшоу вместо работы.
А ещё во время переброса вас ожидает сюрприз, если у вас HDD. Потому что там ОЧЕНЬ много мелких файлов и копирование замедляется.

Проще хранить файлы в обычных каталогах файловой системы.
Я предлагаю вместо ScrapBook использовать UnMHT https://addons.mozilla.org/ru/firefox/addon/unmht/
сохранение страницы со всеми ресурсами одним файлом .mht
Имеются кнопки быстрого сохранения и каталога по умолчанию. Отключения сохранения html5 media и flash. В отличии от стандартного сохранения .mht (который в Opera и Chrome) UnMHT сохраняет дополнительные js скрипты, что делает рабочими спойлеры и подобное.

Единственный плюс ScrapBook X это редактирование страницы. Но как часто это нужно делать да ещё в браузере? Проще использовать сторонний графический редактор HTML или дополнение Print Edit https://addons.mozilla.org/ru/firefox/addon/print-edit/

Если даже UnMHT перестанет разрабатываться всегда можно открыть архив .mht как обычный zip и смотреть страницу как обычный .html Кажется мелочь? Но когда у вас за 1000 страниц, то сам факт что все ресурсы страницы сохранены под одним именем очень помогает.

**Comment by The-OP** [comment]
>Потому что файлы при сохранении не аккуратно сохранены в профиле (по крайней мере были раньше) и я не смог их перекинуть.

Несколько раз прочитал это - так ничего и не понял.

>всегда можно открыть архив .mht как обычный zip

MHT - это не ZIP, а довольно странный формат, кодирующий все в Base64. ZIP - это MAFF, у которого свои проблемы.

Остальное лень разбирать, если честно. Ну могу дописать UnMHT в header, если сильно хочется.
