### ISSUE TITLE
Изменение политики поддерживаемых версий. 

### ISSUE THREAD

**Issue by stepshal** [The-OP/Fox#73]
Может стоит сделать обновление настроек более похожим на выпуск Firefox? Обновлять настройки ветками, а не как в нынешнем виде. Тоесть постоянно добавлять новые настройки и удалять старые в релизной ветке, а когда выходит esr, то просто их замораживать и складывать в папочку esr как legacy. Так в настройках нынешнего релиза не будет удалённых настроек, а в esr новых ненужных. Получится более динамично, но прийдётся оба набора настроек держать и обновлять сразу оба, если изменения и там и там нужны.

**Comment by fake150816** [comment]
ОП, сапушки сам знаешь откуда. Передаю тебе привет от /s и большую-пребольшую просьбу, вот присоединяюсь к оратору выше, если конечно правильно понял его поток сознания. Нужен какой-то способ, чтобы знать, какие настройки добавлять к существующим в prefs/user.js, какие можно удалять спокойно, какие важные блоки зондотерки нельзя пропустить... Есть конечно вот этот пункт "новые настройки в 48", но он не слишком удобен. Мб какие-то дополнительные, альтернативные варианты?

**Comment by The-OP** [comment]
@stepshal 
Стоит много что сделать. Где бы еще времени взять на все. Однако данное предложение считаю нецелесообразным. Ветки я уже делал, но это было когда настройки более старой версии мешали более новой. А если не мешают - зачем?

@fake150816 
История коммитов на что? Неудобно здесь - смотри через `git diff`.

**Comment by stepshal** [comment]
@The-OP 
> Стоит много что сделать. Где бы еще времени взять на все.
Скажи что например, приведи примерный список планов, нужна ли помощь вообще.
