### ISSUE TITLE
Помоги пожалуйста с -no-remote + пара мелких вопросов

### ISSUE THREAD

**Issue by fake150816** [The-OP/Fox#74]
Завел два профиля, запускаю с -no-remote -P.  Профили создаются, несколько разных профилей с разных ярлыков можно запустить поочередно, думаю, несколько РАЗНЫХ FF могли бы работать одновременно. Проблема в другом. Я ввожу в ярлык команды и тем самым лишаю себя возможности открыть еще одно окно этого же профиля с этого ярлыка и, что важнее и страшнее - с панели задач не могу открыть новую вкладку-окно-приватное окно. Ну, вот это вот "правой мышью по иконке фф в панели задач, новая вкладка, новое окно, новое приватное окно. А несколько одновременно открытых профилей группируются и прикрепляются в один и тот же ярлык на панели задач, даже если у ярлыков разные названия и иконки. Раньше вроде как-то можно было нашаманить исправление, но нагуглить у меня не получается, точнее, нагугленное не работает, все эти прикрепить-открепить по очереди и почистить Pinned Tabs/Taskbar руками, либо делаю я их не так. На mozilla-russia и в треде тоже не помогли.
Я хочу вбить эти команды, но не потерять возможность открывать с прилепленного ярлыка новые окна и прилепить к панели задач этот И другой профиль отдельными квадратиками (без разгруппировки то есть). Как быть? Если никак - не стоит ли запилить об этом на багзиллу репорт? Кнопки есть, а не нажимаются - фф уже запущен, но не отвечает...блаблабла, соси хуй.
Есть идеи? Win 8 x64, на 10ке пробовал, на виртуалке с чистым профилем и переустановленным фф тоже пробовал.

И еще вопрос:
Ведь Privacy Badger, получается, зонд?
https://www.eff.org/code/privacy/policy
https://www.eff.org/policy
Как поступить, если мюблок - для совсем пердоликов-хардкорщиков (и даже в минимальном режиме ломает все на свете, яндекс, гугл, ютуб, куб, почту, маркет, вообще все подряд), барсук - сам зонд, да еще и по традиции EFF любит нагрузить систему, гостери тоже зонд... НоСкрипт не ставлю по тем же причинам - каждый первый сайт в исключения добавлять утомляет.

Вот что-нибудь, чтобы поставить и оно само боролось с трекингом...и прочим паразитным трафиком и жаваскриптом? Но само при этом не было зондом, тормозящим систему? И не стоит ли добавить предупреждении о зондоподобности Барсука в шапку?

Ах да, если вдруг ты знаешь, как запилить на стартовую страницу приватного режима свою собственную или about:newtab (что даже лучше) и включить в нем поисковые подсказки в юрл-баре - будет совсем здорово.

**Comment by The-OP** [comment]
Issues этого репозитория предназначены для обсуждения и улучшения находящегося здесь контента, а не техподдержки пользователей Firefox. За последним следует обращаться известно куда.

> Ведь Privacy Badger, получается, зонд?

Нет.

**Comment by wallofbytes** [comment]
> Нет.
Чойта? Я вроде выше ссылкоту даже кинул, там пиздецово
> Issues этого репозитория предназначены для 
Okay...

**Comment by The-OP** [comment]
По ссылке написано, что они могут предлагать что-нибудь отправить, т.е. opt-in.
