### ISSUE TITLE
Screengrab (fix version)  в FAQ

### ISSUE THREAD

**Issue by myBestSoftAndPref** [The-OP/Fox#78]
Предлагаю в раздел https://github.com/The-OP/Fox/blob/master/header.md

> Q: Как сделать скриншот всей страницы? 

Добавить ссылку на Screengrab (fix version) https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/
который многократно облегчает создание скриншотов

**Comment by The-OP** [comment]
Мне не нравятся аддоны этого автора. См. Privacy Policy. Да и скандал был, когда реклама "случайно" оказалась включена по умолчанию в одном из его аддонов.
