### ISSUE TITLE
Дополнение к FAQ для возврата старой строки поиска

### ISSUE THREAD

**Issue by myBestSoftAndPref** [The-OP/Fox#79]
В раздел https://github.com/The-OP/Fox/blob/master/header.md

> Q: Как вернуть старую поисковую строку/старый диалог настроек браузера?

предлагаю добавить ссылку на стиль, который делает поисковую строку очень похожей на старую https://userstyles.org/styles/122214/firefox-search-bar-show-engine-names-firefox-43

**Comment by The-OP** [comment]
d9ad53f
