### ISSUE TITLE
По поводу общего оформления репозитория

### ISSUE THREAD

**Issue by myBestSoftAndPref** [The-OP/Fox#80]
Сейчас ваш репозиторий труднова то читать. Предлагаю вам создать в корне репозитория каталог src и переместить туда все файлы. Затем создать в корне репозитория README.md файл. Он автоматически отобразиться под репозиторием. В этом файле объявить ссылки на основные разделы. Так будет удобнее.

**Comment by The-OP** [comment]
55609cc
