### ISSUE TITLE
Проблемы с Защитой от отслеживания

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#82]
В последних настройках (на FF 47.0.1 по крайней мере):
- user_pref("browser.safebrowsing.provider.google.lists", "");
- user_pref("browser.safebrowsing.provider.mozilla.lists", "");
- user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");

ломают встроенную защиту от отслеживания.
Не особо, конечно, нужная вещь (особо в контексте анонимности и безопасности), но, полагаю, это стоит указать в настройках.

**Comment by The-OP** [comment]
>provider.google.lists

Это не дожно по идее.

>provider.mozilla

А это да, надо пониже перенести, к остальным настройкам tracking protection. (Хотя в этих префах и не только списки tracking protection.)

**Comment by The-OP** [comment]
Перенес в 813232b
