### ISSUE TITLE
security.ssl.disable_session_identifiers

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#85]
user_pref("security.ssl.disable_session_identifiers", true) при большом количестве открытых вкладок, при длительной сессии и длительном времени использования одного и того же профиля замечена в торможении загрузки некоторых сайтов и недозагрузки ресурсов некоторых сайтов.
Предлагаю перенести их "Относительно безопасные" в "Ломающие не особо нужную функциональность".

**Comment by The-OP** [comment]
Куда? Из 3 в 2 что ли?

Такого эффекта не замечал вроде.
