### ISSUE TITLE
Незаслуженно забытый AdGuard и незаслуженно распиаренные uMatrix и PrivacyBadger

### ISSUE THREAD

**Issue by fake150816** [The-OP/Fox#86]
ОП-оп-оппа-па, хуйни AdGuard в спискоту или объясни, почему не хуйнешь. uMatrix ломает сайты даже в самых лайтовых режимах использования, PrivacyBadger делает какую-то непонятную хрень, а AdGuard таки как раз однокнопочная няша, которую можно использовать или вместо, или вместе с uBlock.

**Comment by The-OP** [comment]
В Privacy Policy там достаточно написано.
