### ISSUE TITLE
Добавление WoT в список серых аддонов.

### ISSUE THREAD

**Issue by stepshal** [The-OP/Fox#87]
Читай:
http://www.ghacks.net/2016/11/01/browsing-history-sold/

**Comment by myBestSoftAndPref** [comment]
Причем тут серый список? Его поймали на прямом шпионстве и обмане не только пользователей, но и Google с Moziila. Это уже закопано, выкинуто с репозиториев и не отмоется. Туда и дорога.

**Comment by stepshal** [comment]
А, ну его вообще удалили.

**Comment by The-OP** [comment]
К сожалению, так легко мы от этой гадости не избавились. Так что: d1eb3bf
