### ISSUE TITLE
Firefox 47.0.2

### ISSUE THREAD

**Issue by AlxMxlA** [The-OP/Fox#90]
Что изменилось в этой версии, что теперь при запрете всех видов истории в тех же закладках сохраняется последние добавленные?
Какие-то новые параметры введены разработчиками?
Какие? Как отключить?

**Comment by The-OP** [comment]
В 45 тоже сохраняется. А почему не должно?

**Comment by AlxMxlA** [comment]
Прошу прощения - с закладками разобрался. Там просто немного их отображение сменилось. Хотя, я вот не знаю - фиксирование браузером порядка добавления закладок может как-то влиять на безопасность и анонимность?
И вот `browser.bookmarks.showRecentlyBookmarked` - такого параметра в 45 вроде не было. Может ещё что-то добавили, что, опять таки, может как-то влиять на безопасность и анонимность?

**Comment by The-OP** [comment]
>фиксирование браузером порядка добавления закладок может как-то влиять на безопасность и анонимность

Нет.
