### ISSUE TITLE
Добавление Noscript в список серых аддонов

### ISSUE THREAD

**Issue by stepshal** [The-OP/Fox#92]
https://liltinkerer.surge.sh/noscript.html
https://mailman.stanford.edu/pipermail/liberationtech/2015-April/015236.html

**Comment by The-OP** [comment]
Технически у NoScript есть предупреждение в Privacy Policy о защите от DNS rebinding, для которой ему нужно делать запросы, и способ ее отключения. Но можно подумать.

**Comment by The-OP** [comment]
396aa25
