### ISSUE TITLE
prefs_4.js // Отключает периодическую проверку обновлений аддонов.

### ISSUE THREAD

**Issue by userneu** [The-OP/Fox#95]
https://github.com/The-OP/Fox/blob/master/prefs/prefs_4.js#L255
Эти 4 строчки ломают функцию поиска обновлений, при её ручном запуске. Как в таком случае обновлять расширения? Хотя не в этом конечно суть. Просто описание вводит в заблуждение. Периодическая проверка понимается как самостоятельная деятельность бравзера, когда он периодически делает проверки.

**Comment by The-OP** [comment]
>Как в таком случае обновлять расширения?

Отключить `extensions.update.enabled`, но не очищать url.

**Comment by userneu** [comment]
Спасибо. Мне кажется это нужно пометить в префсах, а то вроде как не очевидно.

**Comment by The-OP** [comment]
Так?
240b107

**Comment by userneu** [comment]
Да, мне нравится. Спасибо!
