### ISSUE TITLE
Про отключение кэширования 

### ISSUE THREAD

**Issue by userneu** [The-OP/Fox#96]
Упоминания есть в двух префсах - №3 и №4. В обоих по 4 команды. Но совпадают только первые две. 
https://github.com/The-OP/Fox/blob/master/prefs/prefs_3.js#L164
https://github.com/The-OP/Fox/blob/master/prefs/prefs_4.js#L1
Почему так и в чем разница?

**Comment by The-OP** [comment]
>в чем разница?

`disk` и `memory`.

**Comment by userneu** [comment]
И правда, мои извинения. Тогда еще в догонку вопрос
https://github.com/The-OP/Fox/blob/master/prefs/prefs_exp.js#L36
Вот здесь про отключение дискового кэша, но без четвертой строчки. Почему так?

**Comment by The-OP** [comment]
Да, это весьма загадочно. Не то, чтобы она сильно нужна была, но добавил для порядка: 0a203c9

**Comment by userneu** [comment]
Да, порядок прежде всего!
