### ISSUE TITLE
AdNauseam - если не добавить, то описать в разделе блокировщиков рекламы

### ISSUE THREAD

**Issue by myBestSoftAndPref** [The-OP/Fox#99]
Нашумевший и возможно даже напугавший Google аддон. Так что Google его даже удалила.
С одной стороны - путает статистику рекламщикам. С другой - лишние действия (запросы). Но они отключаемы. В остальном копия uBlock Origin.
Заслуживает как минимум краткой строчки под описанием uBlock Origin: что это и почему.

www.opennet.ru/opennews/art.shtml?num=45821

**Comment by The-OP** [comment]
> Заслуживает как минимум краткой строчки под описанием uBlock Origin: что это и почему.

>копия uBlock Origin
>7K users

По-моему не заслуживает.

**Comment by myBestSoftAndPref** [comment]
Закрыть глаза на дополнительный функционал и оценивать функции дополнения по количество пользователей?

**Comment by The-OP** [comment]
Про юзеров - это к тому, что около uBO написано о том, почему он, а не другие популярные аддоны. Упоминать там все существующие баннерорезки не вижу смысла.

Что касается функциональности - фичи этого аддона мне кажутся не только бесполезными, но и вредными.

**Comment by The-OP** [comment]
Ладно, пусть будет.

6d15b7d
